- README.md
Update README.md - added information about rich accounts
> Update README.md - added information about rich accounts

- .github/workflows/e2e.yml
* add more permissions to e2e test results
* We are still getting the following error for forked repo PRs `HttpError: Resource not accessible by integration `
Checks pass
> chore: add more permissions to e2e test results

- SUPPORTED_APIS.md
- src/node.rs
- test_endpoints.http
* Add `eth_feeHistory`
* This endpoint is hit by many wallets
MetaMask hitting the endpoint
unit tests:
`era_test_node` vs testnet:
> feat: add eth_feeHistory

- SUPPORTED_APIS.md
- e2e-tests/test/zks-apis.test.ts
- src/cache.rs
- src/fork.rs
- src/http_fork_source.rs
- src/zks.rs
- test_endpoints.http
* impl `zks_getAllAccountBalances`
* impl `zks_getConfirmedTokens`
* Compatibility with mainnet RPC
* Fixes https://github.com/matter-labs/era-test-node/issues/142
> feat: impl `zks_getAllAccountBalances` and `zks_getConfirmedTokens`

- .github/workflows/docs.yaml
- .github/workflows/release.yml
* Updates workflow to make use of rust nightly
* Release workflow and docs broken as it expects nightly
> chore: fix workflows to use nightly

- .github/workflows/docs.yaml
* Fixes docs github action
* It was failing on on the `main` branch due to nightly
> chore: fix docs issue

- src/bootloader_debug.rs
- src/node/in_memory.rs
- src/node/zks.rs
* Update `multivm::vm_virtual_blocks` dependency to `multivim::vm_latest`
* Dependency being used was not the latest one
Ran all tests and e2e-tests.
> feat: update `multivm::vm_latest` dependency

- Cargo.lock
- Cargo.toml
* Updates cargo.toml for upcoming release
* Align with release version
> chore: bump cargo toml for upcoming `0.1.0-alpha.12` release

- src/node/in_memory.rs
* Allow to pass custom tracers to `run_raw_tx`
* To be used downstream for Foundry write-storage manipulation
Unit tests and e2e tests pass
> feat: Allow to pass custom tracers to run_raw_tx

- .github/workflows/tests.yaml
* Updates CI rust nightly
* Foundry-zksync requires 1.74 nightly
> chore: update nightly to reflect foundry-zksync

- .github/workflows/release.yml
* Removes duplicated step in release workflow
* It is not needed as its duplicated 
> chore: remove unneeded step in release workflow

- Cargo.lock
- Cargo.toml
- SUPPORTED_APIS.md
- e2e-tests/test/zks-apis.test.ts
- src/http_fork_source.rs
- src/node/debug.rs
- src/node/eth.rs
- src/node/fee_model.rs
- src/node/in_memory.rs
- src/node/in_memory_ext.rs
- src/node/zks.rs
- src/testing.rs
- src/utils.rs
* gas price was decreased to .05 from .1
* Reflects mainnet, done after alpha.18 release
* 
* 
> fix: l2 gas price was decreased

- Cargo.lock
- Cargo.toml
* Bumps cargo.toml to alpha.19
* Reflects release
> chore: bump cargo toml

- Cargo.lock
- Cargo.toml
- README.md
- example/config.toml
- examples/config.toml
- src/cache.rs
- src/config/cli.rs
- src/config/mod.rs
- src/fork.rs
- src/formatter.rs
- src/http_fork_source.rs
- src/lib.rs
- src/main.rs
- src/node/config_api.rs
- src/node/eth.rs
- src/node/fee_model.rs
- src/node/in_memory.rs
- src/node/mod.rs
- src/node/storage_logs.rs
- src/node/zks.rs
- src/observability.rs
- src/system_contracts.rs
- Adds a file that can be used to configure the test node.
- Config fields provided via CLI take precedence.
- The developer experience of using the test node should be as smooth as possible. 
- This change makes it much easier and faster to create reproducible environment files for different use cases.
- Makes it much easier to get an overview of all the configurable fields for the test node. 
https://github.com/matter-labs/era-test-node/assets/94441036/a779d2c2-561a-49c4-aa6d-5d1ed0fb65f9
_Running the test node with a custom configuration file and then overriding the `l1_gas_price` using the CLI argument_
> feat: config file

- Cargo.lock
- Cargo.toml
* Increase release version to `0.1.0-alpha.26`
* To prepare for the upcoming release
> chore: Update release version

- Cargo.lock
- Cargo.toml
* Increment version
* For upcoming release
> chore: increment version

- Cargo.lock
- Cargo.toml
* The previous version ran into unexpected issues during the release
* Clean up the release :)
> chore: bump version for previous release

- Cargo.lock
- Cargo.toml
Updates zksync deps to https://github.com/matter-labs/zksync-era/commit/7ad0425e00a44e0dd1c3abf38ab2f6335c2f86e7
Required for https://github.com/matter-labs/foundry-zksync upstream sync as it includes https://github.com/matter-labs/zksync-era/pull/2961
Tests pass
> chore: update zksync deps

- src/node/eth.rs
- src/node/in_memory.rs
- src/testing.rs
Makes sure that all block fields are set to reasonable values
See #358 for motivation
> feat: populate block fields

- Cargo.lock
- Cargo.toml
* Bump cargo.toml for next release
* Keep versions correct
> chore: prep for release

- Cargo.lock
- Cargo.toml
* Init release
* Latest changes 
> chore: bump toml for release

- .github/workflows/checks.yaml
- .github/workflows/spec.yml
- spec-tests/src/api.rs
- spec-tests/src/process.rs
- spec-tests/src/utils.rs
- spec-tests/tests/lib.rs
Ditto
Closes #376 
More tests -> more better
> feat(spec-tests): enforce spec-tests in CI

- SUPPORTED_APIS.md
This PR fixes the config API reference in `SUPPORTED_APIS.md`
Commit 28cad46223d3c653952095ec5ec4f67d38177dbe renamed `src/node/config.rs` to be `src/node/config_api.rs`
> fix: update config api reference

- Cargo.lock
- Cargo.toml
* Cut a release before larger anvil-zksync release
* #427 fixes a bug and should be released so users CI action can pick it up
> chore: prepare next release

- src/config/cli.rs
- src/config/mod.rs
- src/main.rs
- src/node/in_memory.rs
* Adds auto-impersonate cli flag
* Updates config accordingly and initializes on startup if true
* Anvil cli parity 
> feat: adds `--auto-impersonate` cli cmd

- SUPPORTED_APIS.md
- e2e-tests/test/anvil-apis.test.ts
- src/namespaces/anvil.rs
- src/node/anvil.rs
Closes #424 
Just anvil aliases for the existing functionality
> feat: add `anvil_snapshot`/`anvil_revert`

- Cargo.lock
- Cargo.toml
- src/main.rs
* Adds back legacy rich wallets
* Bumps toml for release 
* Support backwards compatible 
> chore: add back legacy rich wallets

- e2e-tests-rust/Cargo.toml
- e2e-tests-rust/src/lib.rs
- e2e-tests-rust/tests/lib.rs
- src/main.rs
- src/namespaces/anvil.rs
- src/node/anvil.rs
- src/node/in_memory.rs
- src/node/in_memory_ext.rs
- src/node/mod.rs
- src/node/sealer.rs
Closes #419
Makes `BlockSealerMode` inside `BlockSealer` mutable via `Arc<RwLock<_>>` which allows us to manipulate sealer mode on the fly.
> feat: add `anvil_{get,set}Automine`/`anvil_setIntervalMining`

- Cargo.lock
- Cargo.toml
* Bumps cargo toml
* Align with release
> chore: bump toml

- src/config/cli.rs
Related to https://github.com/matter-labs/zksync-cli/issues/179
Return old host behavior
> fix: default host to 0.0.0.0

- Cargo.lock
- Cargo.toml
* Updates cargo.toml for release 
* Prepares for release
> chore: prepare for release

- e2e-tests-rust/Cargo.lock
Updates e2e test's lockfile
Was forgotten in #514
> chore: update e2e lockfile

- Cargo.lock
- Cargo.toml
* Bumps cargo.toml for v0.2.3 release
* Includes fix for linux binaries 
> chore: prepare for 0.2.3 release

- Cargo.lock
- Cargo.toml
- e2e-tests-rust/Cargo.lock
> chore: prepare for 0.2.4 release

- Cargo.lock
- crates/core/Cargo.toml
- crates/core/src/node/zkos.rs
* Added support for chain_id
* Compute proper gas refunds.
* Updated dependency to be on zk_ee main
> feat: [zkos] added chain id, and proper gas refund

- Cargo.lock
- crates/api_decl/src/lib.rs
- crates/api_decl/src/namespaces/mod.rs
- crates/api_decl/src/namespaces/zkos.rs
- crates/api_server/src/impls/mod.rs
- crates/api_server/src/impls/zkos.rs
- crates/api_server/src/server.rs
- crates/cli/src/cli.rs
- crates/cli/src/main.rs
- crates/config/src/config.rs
- crates/config/src/types/mod.rs
- crates/config/src/types/zkos.rs
- crates/core/Cargo.toml
- crates/core/src/node/eth.rs
- crates/core/src/node/in_memory.rs
- crates/core/src/node/in_memory_ext.rs
- crates/core/src/node/inner/in_memory_inner.rs
- crates/core/src/node/mod.rs
- crates/core/src/node/zkos.rs
- crates/core/src/system_contracts.rs
- docs/rustbook/src/usage/experimental-zkos.md
* allows computing a witness for batch
* and returning it via a new RPC api: zkos_getWitness
* changed the zkos to accept the full config via the command line flags (including path to zkos bin file)
> feat: [zkos] compute and return the witness

- .github/workflows/checks.yaml
- .github/workflows/e2e-docker.yml
- .github/workflows/e2e-rust.yml
- .github/workflows/e2e.yml
- .github/workflows/release.yml
- .github/workflows/spec.yml
- Makefile
- crates/api_server/src/impls/anvil.rs
- crates/api_server/src/server.rs
- crates/cli/src/bytecode_override.rs
- crates/cli/src/main.rs
- crates/core/src/node/debug.rs
- crates/core/src/node/eth.rs
- crates/core/src/node/in_memory.rs
- crates/core/src/node/in_memory_ext.rs
- crates/core/src/node/inner/fork.rs
- crates/core/src/node/inner/in_memory_inner.rs
- crates/core/src/node/inner/mod.rs
- crates/core/src/node/inner/node_executor.rs
- crates/core/src/node/inner/storage.rs
- crates/core/src/node/keys.rs
- crates/core/src/node/mod.rs
- crates/core/src/node/zks.rs
- crates/core/src/utils.rs
- e2e-tests-rust/Cargo.lock
- e2e-tests-rust/src/lib.rs
- e2e-tests-rust/tests/lib.rs
- scripts/refresh_contracts.sh
> chore: merge main

- .github/workflows/tests.yaml
Update github-hosted runner label
Github update runner OS version
> fix(ci): Update github-hosted runner label

- Cargo.lock
- Cargo.toml
* prepare for v0.2.5 release
* Includes replay_tx fix
> chore: prepare for v0.2.5 release

- README.md
Dummy PR replicating https://github.com/matter-labs/anvil-zksync/pull/566 just to re-trigger release-please
> feat!: upgrade to protocol v26 (gateway)

- e2e-tests/test/anvil-apis.test.ts
Messing with one of the rich wallet's nonces can cause unexpected side effects in other tests. We should test on a random wallet instead.
Right now running e2e tests twice on the same instance fails because of this
> test: make `anvil_setNonce` test use a random wallet

- crates/core/src/node/inner/fork.rs
* Adds support for protocol 26 
* Forking is broken as we rolled out 26
> fix: add protocol version 26

- .github/workflows/build-push-docker.yml
- .github/workflows/release-please.yml
> ci: allow gh token to publish docker packages

- Cargo.lock
- Cargo.toml
- crates/core/Cargo.toml
- e2e-tests-rust/Cargo.lock
Get rid of newly introduced dependency on OpenSSL
> chore: get rid of openssl one more time

- Cargo.lock
- deny.toml
> chore: update vulnerable dependencies

- crates/cli/src/cli.rs
- crates/config/src/config.rs
- crates/core/src/node/inner/mod.rs
- crates/core/src/node/inner/vm_runner.rs
* add cli option for bytecode compression
* SHould be configurable and not hardcoded
> feat: add cli option for bytecode compression

- README.md
* Remove dead links from README
* Dead links ain't nice
> docs: remove dead links

- README.md
* Updates readme with l1-l2 communication 
* Should be described
> chore: update readme for l1-l2

- SUPPORTED_APIS.md
- crates/api_server/src/impls/zks.rs
- crates/l1_sidecar/src/lib.rs
This is just a dummy PR that includes minor changes but marking it as breaking to bump next release to `0.4.0`
See above
> feat!: support L1-L2 communication

- Cargo.lock
- Cargo.toml
* updates `zksync-telemetry`
* Latest rev includes https://github.com/matter-labs/zksync-telemetry/pull/9 in preparation to remove custom patch from `foundry-zksync`
Tests pass
> chore: update zksync-telemetry

- crates/common/src/shell.rs
- crates/core/src/formatter/transaction.rs
- crates/core/src/node/inner/vm_runner.rs
* restrict showing balance changes to verbose outputs 
* do not show a header for an empty table with balance changes
* minor refactorings
* improve code quality
* reduce visual noise
Output with `-v`:
```
Warning: Transaction 0xaca6…f4ec was sent to address 0x9887…4ae0, which is not associated with any contract.
✅ [SUCCESS] Hash: 0xaca6dd8a4401ecae6c165cd92ea512503b789071da86f4da5d1649e1a801f4ec
Initiator: 0xf39fd6e51aad88f6f4ce6ab8827279cfffb92266
Payer: 0xf39fd6e51aad88f6f4ce6ab8827279cfffb92266
Gas Limit: 314_153 | Used: 184_816 | Refunded: 129_337
Paid: 0.000008362924000000 ETH (184816 gas * 0.045250 gwei)
Refunded: 0.000005852499250000 ETH
┌──────────────────────────────────────────────────────────────┬──────────────────────────────┬─────────────────────────────┬────────────────┐
│ …
```
> fix: show balance changes only with verbose outputs

- crates/cli/src/cli.rs
- crates/cli/src/main.rs
- crates/cli/src/utils.rs
- docs/book/src/cli/fork.md
- docs/book/src/cli/replay_tx.md
* introduces additional ZK named chains
* Build for elastic network
> feat: introduces additional ZK named chains

- crates/core/src/node/inner/in_memory_inner.rs
Closes #686 
This PR makes gas estimation:
* Decide whether transaction is unexecutable or not early by running VM with max gas first
* Print transaction summary for unexecutable transactions with verbosity level 1 or higher
* Print traces for unexecutable transaction with verbosity level 2 or higher
Better developer experience when debugging unexecutable transactions
With `-vv`:
```
error: Gas estimation encountered unexecutable transaction
error: [anvil_zksync-revert-4] Unknown VM revert reason: function_selector=Error: no function selector available, data=
|
= error: An unknown VM revert reason was encountered.
| 
| Transaction details:
|   Transaction Type: LegacyTransaction
|   Nonce: 0
|   To: 0x000000000000000000000000000000000000800f
|   From: …
```
> feat: print traces for unexecutable transactions during gas estimation

- Formula/anvil-zksync.rb
*  fix sha mismatch from workflow
* Computed wrong sha for binaries - will address in subsequent PR
> fix: fix sha mismatch from workflow

- README.md
- docs/book/src/intro/installation.md
* Updates readme
* Updates versions mentioned in installation docs
* Had too much doc related material in readme that often became outdated. The source of truth should be in user docs
> chore: update readme

- .github/workflows/bump-homebrew-formula.yml
* Fixes issue with computing sha for binaries on release 
* Previously it failed to compute correct sha
> fix: addresses issue with computing sha for binaries for homebrew installation

- crates/cli/src/cli.rs
- crates/cli/src/main.rs
- crates/config/src/config.rs
- crates/core/src/node/in_memory.rs
- crates/core/src/node/inner/in_memory_inner.rs
- crates/core/src/node/inner/vm_runner.rs
- crates/core/src/system_contracts.rs
- docs/book/src/README.md
- docs/book/src/cli/index.md
- docs/book/src/intro/index.md
- e2e-tests-rust/tests/evm.rs
* update naming conventions for evm interpreter and boojumos
* Keep consistent and accurate
> chore: update naming conventions for evm interpreter and boojumos

- crates/cli/src/main.rs
- crates/config/src/config.rs
- crates/config/src/types/boojum.rs
- crates/config/src/types/mod.rs
- crates/core/src/node/boojumos.rs
- crates/core/src/node/in_memory.rs
- crates/core/src/node/inner/in_memory_inner.rs
- crates/core/src/node/inner/vm_runner.rs
- crates/core/src/node/keys.rs
- crates/core/src/node/mod.rs
- crates/core/src/node/vm.rs
- crates/core/src/system_contracts.rs
* Added boojum config (as I need to pass more parameters)
* renamed zkos to boojum.
> chore: Added boojum config and renamed zkos to boojum

- e2e-tests-rust/src/ext.rs
- e2e-tests-rust/tests/revert.rs
* fix linter warnings in e2e tests
> fix: linter warnings

- docs/book/src/SUMMARY.md
- docs/book/src/guides/protocol-upgrade-steps.md
* Adds guide for protocol upgrade flow
* Should exist in docs as a reference
Run `make docs-site` to view.
> chore: docs update book to include upgrade flow

- Cargo.lock
- Cargo.toml
- crates/core/Cargo.toml
- crates/core/src/node/zksync_os/real/helpers.rs
* First thing updated with this PR
* Second thing updated with this PR
* Third thing updated with this PR
* Reason why first thing was added to PR
* Reason why second thing was added to PR
* Reason why third thing was added to PR
> feat: Update ZKsync OS to v0.0.5
