Cargo.lock
Cargo.toml
src/formatter.rs

* Increase padding of addresses
* Improve padding alignment for function signatures
* Update the background color to red for stack calls that are errors or reverts
* Increased the version from `1.0.0` to `1.0.1`
* When there are multiple nested calls, their addresses (when not converted to a human readable format) start to misalign the content to the right, making things difficult to read
* Function signatures have all sorts of quirky styling (some due to `colorize` cargo oddities), but with the right-aligned formatting, it fixes 90% of the issues
* Having the background color for errors be red makes troubleshooting faster, as running a command like `replay_tx` can stream a lot of calls in rapid succession. This will make Errors immediately noticeable. 
* Updating the version seemed like …

Update formatting of call stacks in `zksync_test_node` CLI

---

src/formatter.rs
src/node.rs

- Implements `get_block_number` 
- Adds placeholder values for `estimate_gas` and `gas_price` 
- Constructs and adds `logs` to `get_transaction_receipt` 
- Formats using `cargo fmt` 
- The current implementation did not have these fields populated so deployment transactions were being stuck in an infinite loop and never resolving the necessary promises. A more detailed review of the issue can be found here: https://github.com/matter-labs/era-test-node/issues/8
- Closes #8 
- Successfully deploys tutorial `Greeter.sol` contract 
**era-test-node console**
```
Executing 0x44a66ef7c96b228f8bdeed592ae123714b7533775c5c67e900317f204b11ec68
Transaction: SUCCESS
Initiator: 0x36615cf349d7f6344891b1e7ca7c72883f5dc049 Payer: 0x36615cf349d7f6344891b1e7ca7c72883f5dc049
Gas Limit: 80000000 used: …
```

feat: implements required api methods for deploying contracts with `hardhat-zksync-deploy` plugin

---

Cargo.toml
README.md

**Changes introduced in this PR:**
- Renames binary to `era_test_node` from `zksync_test_node`. I think its best to keep the repository name and binary alike, this also serves to avoid confusion when referencing `era_test_node` on the docs site.  
- Updates README accordingly

chore: rename binary to era_test_node from zksync_test_node

---

Cargo.lock
Cargo.toml
src/fork.rs
src/formatter.rs
src/main.rs
src/node.rs
src/zks.rs

* Update dependencies to latest on zksync-era
* Updates node.rs and zk.rs to return a BoxFuture type from the jsonrpc_core library
* To reflect the latest changes in zksync-era and fix errors with compiling and running cargo install
Run: `make rust-build` 
Closes #13 Closes #14

chore: fixes compile error

---

.github/CODEOWNERS
.github/CONTRIBUTING.md
.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/config.yml
.github/ISSUE_TEMPLATE/feature_report.md
.github/workflows/checks.yaml
.github/workflows/secret_scanner.yaml
.github/workflows/tests.yaml
Cargo.lock
Makefile
README.md
src/console_log.rs
src/formatter.rs
src/main.rs
src/node.rs
src/resolver.rs
src/zks.rs

* Updated the README.md 
* Adds templates for issues
* Added CONTRIBUTING.md 
* Added CODEOWNERS
* Added CI checks for linting, tests, build, and secret scanner
* Adds single unit test for demonstration and CI 
* Updates makefile
**Note:** Clippy is currently set to ignore `unwrap()` but we will update once we handle errors more gracefully. 
* Step towards standardizing repos, these changes adds necessary structure and controls. The templates, readme, and contributing file are certainly opinionated so please feel free to add suggested changes.  
* Any notes/thoughts that the reviewers should know prior to reviewing the code?

Updates readme, adds templates, updates makefile, and adds CI

---

.gitignore
.vscode/extensions.json
Cargo.lock
Cargo.toml
README.md
SUPPORTED_APIS.md
src/configuration_api.rs
src/main.rs
src/node.rs
test_endpoints.http

* Add new configuration RPC endpoints (`config_getShowCalls`, `config_setShowCalls`, and `config_setResolveHashes`)
* Add example http REST file for quickly testing the node locally
* Add recommended plugins for VSCode
* These endpoints help update the configuration of stream output from the in-memory node without requiring a restart of the node (potentially losing information)
* Having the `.http` file has made an easy way for developers to make requests to the available RPC endpoints without memorizing or copy/pasting long CURL commands
* Recommended plugins will help developers use `.http` files and setup their local environment faster
In this video, I start a node with just `era_test_node run` and update the `--show-calls` and `--resolve-hashes` parameters via RPC calls while the node …

Add new configuration RPC endpoints

---

src/node.rs

* Implementation of `get_transaction_by_hash` RPC endpoint
* Some operations done in the [zksync-era Rust SDK](https://github.com/lambdaclass/zksync-web3-rs) need the implementation of this method to get the transaction receipts.
This video demonstrates a test for contract deployment using the `era-test-node` with the `Rust SDK`. The deployment process completes successfully once it can retrieve the transaction receipt. The receipt is obtained using the `get_transaction_by_hash` endpoint and then printed in the console.
https://github.com/matter-labs/era-test-node/assets/63374472/99fc9d45-dd70-47a0-8a40-d12604983a4e
* This implementation may be incorrect and not entirely accurate. I used the other implementations as a reference.

Implement get transaction by hash rpc endpoint

---

.gitignore
.vscode/launch.json
.vscode/tasks.json

* Add debugging configurations for VSCode
* To make debugging the application a one-click process (especially if you want to debug local contracts)
https://github.com/matter-labs/era-test-node/assets/1890113/28c43f24-2efb-4227-a9ed-33a486fd7fdb

Add debugging configurations for VSCode

---

.github/workflows/checks.yaml
.github/workflows/release.yml
.github/workflows/tests.yaml
Cross.toml
Makefile
docs/release.md

* Adds `release.yaml` to the CI
* Adds push tag workflow trigger for check and test workflows
* Updates ci deps for rust cache
* Adds make command
* Adds a `Cross.toml` file for `release.yaml` workflow
* Automates the preparation of binaries for multiple targets and drafts a release. 
* When we push a tag (e.g. `v0.0.1-alpha`) it will trigger the test, checks, and release workflows 
* Outdated CI dep 
* `make rust-<target>` command added to makefile for ci convenience and readability 
* Toml file is used for cross configuration in the ci. See docs here: [cross](https://github.com/cross-rs/cross#option-2-configuring-cross-via-a-crosstoml-file) 
The release will be presented as such 👇 :
Specifics on the release workflow 👇 
This PR introduces a new release pipeline aimed at automating the …

ci: adds release workflow for automated draft releases

---

.github/workflows/release.yml
Cargo.lock
Cargo.toml
Makefile
docs/release.md

* Add `new-release-tag` command to Makefile
* Update version of rust crate to match GitHub release version
* Update release template
* To better automate the management of versions and consolidate to just the `Cargo.toml` file
* Having the versions match reduces confusion for end users
* We manually removed `Critical` adjective during the latest pre-release, so adding that change here permanently

chore: Update version of rust crate to match latest GitHub Release

---

SUPPORTED_APIS.md
src/zks.rs
test_endpoints.http

* Implement `zks_getTokenPrice` endpoint
* Update support for `eth_estimateGas` and `zks_estimateFee`
* Fix incorrect links in `SUPPORTED_APIS.md`
* This is used by the Portal dApp
* The support levels were incorrect for gas estimation now that https://github.com/matter-labs/era-test-node/pull/31 is merged
* Links to source code were incorrect
Unit tests are passing:

feat: implement zks_getTokenPrice endpoint

---

Cargo.toml

* Increase version in `Cargo.toml`
* To match `0.1.0` release (Releases/tags are still manually managed while awaiting automation blockers)

chore: Bump version of Cargo.toml

---

SUPPORTED_APIS.md

* Add associated GitHub Issues within the table
* Update the `Work In Progress` banner
* Alphabetize the API endpoints
* Move the Status Key before the table of endpoints
* Update support status for `eth_getTransactionReceipt`
* Add `default` values within the Description column
* Update description of `eth_getBlockByNumber`
* Add more missing APIs to the table
* Having the GitHub Issues next to the status encourages users to implement/fix the endpoints. It's also easier to see at a glance which endpoints have been prioritized for future implementation.
* Having the banner mention GitHub Issues will encourage user engagement of the repo.
* Makes the table easier to search
* The Status is important to understand the information in the table is the "current state of the world"
* The …

docs: Update SUPPORTED_API.md with GitHub Issues, missing endpoints, and latest information

---

.github/workflows/docs.yaml

* Adds rust docs GitHub workflow
* This will produce API documentation for the code, so we don't need to maintain separate docs repeating information from inline comments
Running `make rust-doc` locally:
* From what I've researched, there's no good way to test the publish of GitHub Pages without the workflow deployed to `main` branch

docs: Adds rust docs GitHub workflow

---

Cargo.lock
src/configuration_api.rs
src/formatter.rs
src/lib.rs
src/main.rs
src/node.rs
src/zks.rs

* Adding lib.rs that allows other rust programs to include era-test-node as a library
* moved ShowCalls into this crate (before it was in main.rs)
* This allows other rust programs (for example forge testing) to include era test node as a library.
You can include era-test-node from other crates.
```
[dependencies]
era_test_node = {path = "../era-test-node"}
```

Make era-test-node a library

---

Cargo.lock
src/configuration_api.rs
src/fork.rs
src/http_fork_source.rs
src/lib.rs
src/main.rs
src/node.rs
src/zks.rs

* Adding ForkSource trait that hides the code responsible for querying the original repository data
* Currently there is only one implementation for this ForkSource -- the HttpForkSource that fetches data over internet.
* This allows more flexibility when era-test-node is used as a library - for example for Forge, we'll be able to implement the ForkSource that uses REVM database instead.

Adding ForkSource trait

---

.github/workflows/release.yml
Cargo.toml
Cross.toml

* Installs cross from source
* Adds req deps to `Cross.toml` and `Cargo.toml`
* Installing cross from source provides newest image for `x86_64-unknown-linux-gnu`
* Updated `Cross.toml` to include new required deps from rocksdb version update to `0.21.0` 
* Adds `openssl-sys` vendored copy so binary can be distributed with openssl so it can be executable without installing additional deps
**Release pipeline succeeding from fork:**
**x86_64-unknown-linux-gnu libraries available:**
Closes #90

fix: resolves #90 | fixes release executable and headers issue

---

.github/workflows/e2e.yml

* Fix permissions for e2e test results
* E2E tests are failing with `Error: HttpError: Resource not accessible by integration`
See checks for this PR

chore: fix permissions for e2e test results

---

.github/workflows/e2e.yml
e2e-tests/test/main.test.ts
scripts/execute-e2e-tests.sh

* Remove e2e test reports
* They provide little value as they pass 99% of the time, and print out failures/results to the console
Verified that when e2e tests fail, the job fails and still prints out the output of the `era_test_node` binary
* The original commit contains a failed test to validate that the logs of the `era_test_node` binary will still be output as expected

chore: remove e2e test reports

---

e2e-tests/contracts/Greeter.sol
e2e-tests/package.json
e2e-tests/test/main.test.ts
e2e-tests/yarn.lock
src/node.rs

* Display the revert reason when calls or gas estimations fail
* Added negative e2e test
* This data provides a lot of clarity for reverts that could appear to just be gas estimation failures
* Need to validate the node can correctly handle expected failures for negative testing
* NOTE: This will probably be one of the final e2e tests as we want to invest more into unit/integration tests for the immediate future. We just needed to validate that we've unblocked negative testing for hardhat.
Results of added e2e test:

feature: display the revert reason when calls or gas estimations fail

---

SUPPORTED_APIS.md
src/hardhat.rs
test_endpoints.http

Nb- depends on https://github.com/matter-labs/era-test-node/pull/91
Add `hardhat_setNonce` implementation
* Allow users to manipulate account nonces on dev node
* In Era we have two nonces (account and deployment) - Principle of Least Astonishment dictates that we set both to the requested nonce (and fail if either of them are greater than the requested nonce).
* Alternatively we could extend this method to accept another argument to allow setting the nonces separately
* resolves https://github.com/matter-labs/era-test-node/issues/77

feat: implement hardhat_setNonce

---

.github/CODEOWNERS
.github/workflows/check-pr-title.yml
SUPPORTED_APIS.md

* Enforce conventional commits on PRs (merges to `main` branch)
* Update `CODEOWNERS` to be entire team
* Fix broken link in `SUPPORTED_APIS.md`
* Standardized and automated release notes
* To keep the list of engineers more open as the team changes over time
* Link was malformed
TBD (I'm unable to validate with the current run criteria, so will merge and validate in subsequent PR to ensure permissions are correct)
* This works as a level of enforcement because we only allow squash merging of PRs
* See [Conventional Commits Spec](https://www.conventionalcommits.org/en/v1.0.0/) for more information

chore: enforce conventional commits on main

---

.github/workflows/release.yml

* Add Contributors section to Releases
* Slight revisions to Release default format
* Include this commit [f68093cfbe4c4c2e8ea2c0c67ff172e2e0be7289](https://github.com/matter-labs/era-test-node/commit/f68093cfbe4c4c2e8ea2c0c67ff172e2e0be7289)
* To ensure credit is given to all contributors of releases
* This better matches the latest release notes we've published (leading to fewer manual changes for us from draft to release)
* It was necessary for the previous release, but was never merged into `main`
For tag `v0.1.0-alpha.2`:
```bash
$ git log --pretty=format:"- %aN (%aE)" $(git describe --tags --abbrev=0 v0.1.0-alpha.2^)..v0.1.0-alpha.2 | sort | uniq
- Dustin Brickwood (dustinbrickwood204@gmail.com)
- Marcin M (128217157+mm-zk@users.noreply.github.com)
- Nicolas Villanueva …
```

chore: add contributors to draft release template

---

src/main.rs

* Updated RPC server binding address from `127.0.0.1` to `0.0.0.0`
* To allow access to the in-memory node both via `http://localhost:8011` and `http://127.0.0.1:8011`
* To ensure compatibility with Docker containerization
* Previously it wasn't possible to access in memory node on `http://localhost:8011` from the browser.

fix: bind server to 0.0.0.0 for external access

---

e2e-tests/package.json
e2e-tests/yarn.lock
etc/system-contracts/hardhat.config.ts
etc/system-contracts/package.json
etc/system-contracts/scripts/compile-yul.ts
etc/system-contracts/yarn.lock

* Bump hardhat zksync deploy and solc versions
* Fetches binaries from GH Releases CDN instead of repositories (related to `Headers Timeout Error`s found last week)

fix: Bump hh deploy and solc versions

---

.gitignore
Cargo.lock
Cargo.toml
README.md
src/cache.rs
src/fork.rs
src/formatter.rs
src/hardhat.rs
src/http_fork_source.rs
src/lib.rs
src/main.rs
src/node.rs
src/testing.rs

* Adds a caching layer to the http fork source.
* Adds `--cache` command line parameter to either:
* `none` - disable caching
* `memory` - in-memory caching
* `disk` - persisted on-disk caching
* Adds `--cache-dir` & `--reset-cache` options to disk caching to select the cache location and whether to purge cache on startup, respectively
* During testing it is quite often intended to run similar requests multiple times. Having a cache reduces the required number of network calls to be made.
* Fixes #106

feat: Add caching to HttpForkSource

---

SUPPORTED_APIS.md
src/fork.rs
src/http_fork_source.rs
src/node.rs
src/testing.rs
test_endpoints.http

* Adds support for `eth_getBlockTransactionCountByHash`
* Adds support for `eth_getBlockTransactionCountByNumber`
* Improves `testing` server
* Users might need to view the number of transactions contained in a block by its hash or by the number.
* It is beneficial to generate raw json for blocks and transactions instead of the response object during testing as many objects are composable.
* Fixes #43 
* Fixes #44

feat: Add eth_getBlockTransactionCountByHash and eth_getBlockTransactionCountByNumber

---

SUPPORTED_APIS.md
src/evm.rs
src/hardhat.rs
src/node.rs
src/utils.rs
test_endpoints.http

* Adds `evm_mine` as supported RPC method
* Adds `hardhat_mine` as supported RPC method
* Adds tests/docs
* Allows user to manually trigger a new block(s) to be mined
* Seems quite a lot of setup for rolling new block

feat: impl `evm_mine` and `hardhat_mine`

---

README.md

* Updates readme to include latest transaction logging options, and references GH action for CI usage.
* Information on these items are not available anywhere else atm
* Any notes/thoughts that the reviewers should know prior to reviewing the code?

chore: updates readme with latest changes

---

Cargo.lock
Cargo.toml
src/hardhat.rs
src/logging_middleware.rs
src/main.rs
src/node.rs
src/testing.rs

* Add logs for incoming API requests
* Update `not_implemented` logs to warnings
* Update version number to match latest release
* Fix unit test
* This shows a clearer picture of what's happening against the node. When debugging an interaction with other tools like MetaMask, Portal, Block Explorer, etc. it's VERY useful to know what requests have been made and might be silently failing
* Warning better encapsulated the response now that it's contrasted against the initial request
* This was out of date per the latest release
* Overlooked prior to merge of a refactor when implementing `eth_feeHistory`
Example of new `not_implemented` logs:
Output of `make test-e2e` with default logs:
Output of `eth_getBlockByNumber` with `trace` log level:
* I chose to reference the `LevelFilter` in the …

feat: add logs for incoming API requests

---

Cargo.lock
Cargo.toml

* Updated the dependency on zksync-era to v6
* this is basically the same as we use today, so there are no changes.
* zksync era is doing a major release, that contains a large VM api change
* so we have to clean up our dependency versions, so that era-test-node doesn't get broken 
* as previous commit of zksync-era that we depended on, have sub-dependencies that will be broken soon

chore: updated zksync era dependency to v6.0.0

---

Cargo.lock
Cargo.toml
SUPPORTED_APIS.md
src/filters.rs
src/formatter.rs
src/hardhat.rs
src/lib.rs
src/main.rs
src/node.rs
src/testing.rs
test_endpoints.http

* Adds support for `eth_newBlockFilter`, `eth_newFilter`, `eth_newPendingTransactionFilter`, `eth_uninstallFilter`, and `eth_getFilterChanges`.
* Keeps track of transaction logs in node.
* Filters are a quite common use case that enables developers to get the exact information they are interested in, quickly.
* Fixes #36 
* Fixes #37
* Fixes #38
* Fixes #39
* Fixes #42

feat: add filter support

---

src/filters.rs
src/node.rs
src/utils.rs

* add utility function to convert `BlockNumber` to actual numbers
* Common use case in the codebase
* Follow up to #124

chore: add utility function to convert block numbers

---

SUPPORTED_APIS.md
src/hardhat.rs
src/node.rs
src/utils.rs
test_endpoints.http

* Adds a field `impersonated_account: Option<Address>` to node; in `run_l2_tx` method, adjust the tx to have initiator = impersonated account if set. This requires setting `self.system_contracts = SystemContracts::from_options(&Options::BuiltInWithoutSecurity)` to disable signature verification
* Adds `hardhat_impersonateAccount` and `hardhat_stopImpersonationAccount` RPCs
* Allow user to send transactions from arbitrary addresses, useful for testing
* Any suggestions for better tests? We don't have any test for `send_raw_transaction`- I tried a bit to write one but was quite hard, just re-used `apply_txs`

feat: impl `hardhat_impersonateAccount` and `hardhat_stopImpersonationAccount`

---

SUPPORTED_APIS.md
src/filters.rs
src/node.rs
src/testing.rs

* adds `eth_getLogs` and `eth_getFilterLogs`
* Method to fetch _all_ logs matching a criteria.
* Fixes #40  & #41

feat: add eth_getLogs and eth_getFilterLogs

---

Cargo.lock
Cargo.toml
SUPPORTED_APIS.md
e2e-tests/helpers/constants.ts
e2e-tests/test/eth-apis.test.ts
src/node.rs
test_endpoints.http

* Adds `eth_accounts` endpoint
* Updates `get_transaction_by_hash` to retrieve transaction from fork if unavailable
* Bumps cargo.toml to latest version
* Unsupported API was needed to work alongside [Rivet](https://github.com/paradigmxyz/rivet) 
* Previously was not returning tx's when unavailable in local memory 
* Was set to an outdated version 
---
* Any notes/thoughts that the reviewers should know prior to reviewing the code?

feat: adds `eth_accounts` and updates `get_transaction_by_hash` to retrieve from fork if needed

---

src/node.rs

* Update `eth_call` to serialize output data in console
* So it's easier to read
This is purely a cosmetic change in the console logs
BEFORE:
```
19:36:22 [INFO] Call: SUCCESS [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 32, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 72, 105, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
19:36:22 [INFO] === Console Logs: 
19:36:22 [INFO] === Call traces:
```
AFTER:
```log
20:03:06 [INFO] Call: SUCCESS
20:03:06 [INFO] Output: "0x00000000000000000000000000000000000000000000000000000000000000200000000000000000000000000000000000000000000000000000000000000002486900000000000000000000000000000000000000000000000000000000 …
```

chore: update eth_call to serialize output data in console

---

e2e-tests/test/evm-apis.test.ts
e2e-tests/test/hardhat-apis.test.ts
src/evm.rs
src/hardhat.rs
src/node.rs
src/testing.rs
src/utils.rs

* Aligns current_miniblock, current_batch, current_timestamp to point to the latest entities. Previously current_miniblock would contain the latest block but others would contain values for the next block
* Fix `compute_hash` type for block_number being `u32` instead of `u64`
* Fixes behavior mining blocks according to the `current_timestamp` rules.
* The code should not be confusing to any new contributors and must be consistent.
* All tests pass
* New tests for creating empty blocks
* Fixes #131

chore: align current_miniblock, current_batch, current_timestamp to point to the latest entities

---

src/zks.rs

* Updates `get_l1_batch_details` to return properly formed `null` response
* Although L1 communication is currently not supported, for block explorer integration this method is required to respond with a properly formed response. This will now always respond with `{"jsonrpc":"2.0","result":null,"id":1}` for this reason. 
CC: @vasyl-ivanchuk 
* Any notes/thoughts that the reviewers should know prior to reviewing the code?

chore: adds proper null response to zks_batchDetails method

---

Cargo.lock
Cargo.toml
src/console_log.rs
src/node.rs

* Update version of `zksync-era` to include the call stack fix
* Add dependency on `chrono`
* Provide default block hash during L1 batch creation
* Determine call stack count using first call from trace
* This fixes the console logs and adds back the call stack
* `zksync_dal` updated their use of some DateTime functions to pull from the `sqlx` version of `chrono`
* An upstream change updated the logic for `load_last_l2_block`
* Call stacks now have a single root, so using `.len()` will always return 1 if there are any call traces. 
`make test-e2e`:
Same e2e tests but with `--show-calls`:

fix: add back call stacks, console logs, and correct call stack count

---

SUPPORTED_APIS.md
src/node.rs
test_endpoints.http

* adds `eth_protocolVersion` with the current [version](https://github.com/ethereum/devp2p/blob/master/caps/eth.md#eth63-2016) being `63` (same as ganache)
* Feature parity for the `eth_` namespace.
* Fixes #48

feat: add eth_protocolVersion

---

.github/workflows/release.yml

* adds aarch64-unknown-linux-gnu target
* Allows building for aarch64 platform
https://github.com/Moonsong-Labs/era-test-node/actions/runs/6248332681/job/16962735340
* Fixes #56

fix: add aarch64-unknown-linux-gnu target

---

.github/workflows/docs.yaml

* installs `mdbook` for ci, so the rustbook can be generated
* This is currently not working on `main`
https://github.com/matter-labs/era-test-node/actions/runs/6481038664/job/17597775592

fix: install mdbook for ci

---

.github/workflows/release.yml

* Replaces `hub` for `gh`
* `hub` is being removed from runners in favour of `gh`

chore: remove hub usage in favour of gh for draft releases

---

.github/workflows/docs.yaml
SUPPORTED_APIS.md
e2e-tests/contracts/Return5.sol
e2e-tests/test/hardhat-apis.test.ts
src/hardhat.rs
test_endpoints.http

* adds `hardhat_setCode`
* Allows developers to set arbitrary smart contract bytecodes for a given address, aiding in development.
* Fixes #149

feat: add hardhat_setCode

---

Cargo.lock
Cargo.toml
SUPPORTED_APIS.md
e2e-tests/test/zks-apis.test.ts
src/fork.rs
src/http_fork_source.rs
src/utils.rs
src/zks.rs
test_endpoints.http

* Added `get_transaction_details` to `http_fork_choice`
* Implemented handler for `zks_getTransactionDetails` to zks namespace
* Allow users to retrieve tx details
* We are not caching these responses due to their mutable status. We could cache when `status == Finalized`, but didn't seem worth it. wdyt?
* Fixes https://github.com/matter-labs/era-test-node/issues/146

feat: impl `zks_getTransactionDetails`

---

SUPPORTED_APIS.md
e2e-tests/test/zks-apis.test.ts
src/fork.rs
src/http_fork_source.rs
src/zks.rs
test_endpoints.http

* Adds `zks_getBlockDetails` RPC
* User can get zksync-specific info about blocks
* fixes https://github.com/matter-labs/era-test-node/issues/143

feat: impl zks_getBlockDetails

---

README.md
src/main.rs

* Adds support for `builtInWithoutSecurity` option via `--dev-system-contracts` parameter, which can take the following options:
* `built-in`: Use the compiled built-in contracts
* `built-in-no-verify`: Use the compiled built-in contracts, but without signature verification
* `local`: Load contracts from `ZKSYNC_HOME`
* Remove `--dev-use-local-contracts` in favor of  `--dev-system-contracts` 
* Allows easier debugging of local setups
* Fixes #105

feat: support builtInWithoutSecurity option

---

SUPPORTED_APIS.md
e2e-tests/test/zks-apis.test.ts
src/cache.rs
src/fork.rs
src/http_fork_source.rs
src/testing.rs
src/zks.rs
test_endpoints.http

* Adds `zks_getBridgeContracts` rpc. This returns the default values in local `run` mode and queries the fork in `fork` mode.
* Required for the block explorer
* Fixes #153

feat: add zks_getBridgeContracts

---

Cargo.lock
Cargo.toml
README.md
SUPPORTED_APIS.md
src/cache.rs
src/configuration_api.rs
src/console_log.rs
src/evm.rs
src/filters.rs
src/fork.rs
src/formatter.rs
src/hardhat.rs
src/http_fork_source.rs
src/lib.rs
src/logging_middleware.rs
src/main.rs
src/node.rs
src/observability.rs
src/system_contracts.rs
src/utils.rs
src/zks.rs
test_endpoints.http

* Removes `vlog`, `log`, and `simplelog` in favor of `tracing` and `tracing-subscriber` crate for logging.
* Adds `config_setLogLevel` and `config_setLogging` to dynamically control logging parameters.
* Introduce `InMemoryNodeConfig` to contain all behavior-related parameters to avoid `InMemoryNode::new()` from having too many parameters.
* Less redundant dependencies
* Easy logging control during runtime
* Better code quality
```sh
cargo run -- run
```
```sh
cargo run -- --log=trace --log-file-path=foo.log run
```
* Fixes #133

feat: refactor logging to use tracing crate and make it dynamic

---

SUPPORTED_APIS.md
e2e-tests/test/zks-apis.test.ts
src/zks.rs
test_endpoints.http

* Add `zks_getRawBlockTransactions` method
* Users can retreive raw transactions per block 
* fixes https://github.com/matter-labs/era-test-node/issues/141

feat: impl zks_getRawBlockTransactions

---

src/node.rs

* support `max_fee_per_gas` and `max_priority_fee_per_gas` for `eth_sendTransaction`
* These fields are used by hardhat/ethers while using `SignerWithAddress`(relevant for account impersonating)

fix: support EIP-1559 fields for eth_sendTransaction

---

src/zks.rs

* Unit tests are currently broken on `main`
* `main` should be running tests
https://github.com/matter-labs/era-test-node/actions/runs/6571609788/job/17851103610

fix: fix unit tests on main

---

Cargo.lock
Cargo.toml
src/fork.rs
src/node.rs
src/testing.rs
src/zks.rs

* fixed forking for zksync-era@16.0.2 after https://github.com/matter-labs/zksync-era/pull/211 was merged
* Forking needs to work for majority of use cases
* Fixes #190

fix: fix forking for zksync-era@16.0.2

---

.github/workflows/release.yml

* Fix `gh` CLI command for creating GitHub Release drafts
* It's currently broken as the previous `hub` CLI tool accepted `-a <file_name>`
Validated with release on my personal fork: https://github.com/MexicanAce/era-test-node/releases/tag/v0.0.3-nick
NOTE: Release drafts will NOT properly have a tag in the release URL. So the links to download the binaries in the table only work one the Release has been published

fix: Release drafts now attach files correctly

---

.github/workflows/checks.yaml
.github/workflows/tests.yaml
Cargo.lock
Cargo.toml
src/bootloader_debug.rs
src/debug.rs
src/formatter.rs
src/node.rs
src/system_contracts.rs
src/testing.rs
src/utils.rs
src/zks.rs

* Updates zksync-era deps to `73a1e8ff564025d06e02c2689da238ae47bb10c3` 
* Replaces `vm` with `multivm` 
* Downstream dependencies of era-test-node, mainly `era-revm` require latest changes in `multivm`

chore: updates zksync dep, and replaces vm with multivm crate

---

src/node/eth.rs
src/node/in_memory.rs
src/utils.rs

- Fixed issue with incorrect genesis block hash mapping. Genesis block has `hash = compute_hash(block_number, H256::zero())`, but in mapping just `H256::zero()` was used. So `get_block_by_hash(compute_hash(block_number, H256::zero()))` call didn't work, as mapping was incorrect.
- Added `parent_hash` link to each block pointing to previous block hash. Genesis block `parent_hash` points to `H256::zero()`.  For produced blocks previous block hash is used, for `create_empty_block` if `parent_hash` is not provided it generates `parent_hash` assuming previous block used the same hash generation method.
- Added default `0` value for `transaction.gas_price` and default `H256::zero()` value for `tx_receipt.root` as normally these fields should never be undefined.
- fixes `get_block_by_hash` API …

feat: add parent hash linking for blocks

---

Cargo.lock
Cargo.toml
src/deps/mod.rs
src/fork.rs

* Update `zksync-era` dependency to commit hash with `Version17`
* Add `get_enumeration_index` to Storage (hard-coded to 0 for now)
* Add `Version17` as supported version for HttpForkSource
* Increase cargo version
* To fix `era_test_node fork mainnet` and `era_test_node fork testnet`
* These values were added and required for Boojum upgrade
* `Version17` is now supported from upstream forks
* Upcoming release (with these fixes) will be `v0.1.0-alpha.10`
Unit/E2E Tests Pass (See CI builds for PR)
`era_test_node fork mainnet` works:
`era_test_node fork testnet` works:

chore: Update zksync-era dependency to latest

---

rust-toolchain.yaml
src/node/in_memory.rs

* Adds rust toolchain.yml
* Makes `run_l2_tx_inner` public
* Ensures everyone is using the same rust nightly given the instability and experimental features 
* `era-revm` is dependent on being able to call `run_l2_tx_inner`

chore: add rust toolchain for version mgt, make inner_tx pub

---

src/node/eth.rs

Change `eth_getBlockByNumber` and `eth_getBlockByHash` to return `null` for non existing block.
According to Ethereum [JSON RPC spec](https://ethereum.org/en/developers/docs/apis/json-rpc/#eth_getblockbyhash) these methods should return `null` when no block was found.
> Returns
> Object - A block object, or null when no block was found:
Since the test node doesn't fully follow the standard for these methods and throws an error instead of returning a `null` result, Block Explorer interprets it as an error and retries the request. This may also occur with other tools.
L1 and L2 networks return `null` for non existing blocks as expected.
```
% curl http://127.0.0.1:8011 \
-X POST \
-H "Content-Type: application/json" \
--data '{"method":"eth_getBlockByNumber","params":["0x123",false],"id":1," …
```

feat: get block returns null for non existing blocks

---

SUPPORTED_APIS.md
e2e-tests/test/evm-apis.test.ts
e2e-tests/test/web3-apis.test.ts
src/fork.rs
src/http_fork_source.rs
src/main.rs
src/namespaces/mod.rs
src/namespaces/web3.rs
src/node/debug.rs
src/node/mod.rs
src/node/web3.rs
src/node/zks.rs
test_endpoints.http

* Implement `web3_clientVersion`
* Fix test for `evm_snapshot`
* Add `fork` support for `Version9`, `Version10`, `Version11`, and `Version12`
* This is necessary for some hardhat plugins
* The test was flaky/failing when being run more than once
* These versions are supported and shouldn't error out with `fork` or `replay_tx`
E2E tests pass
* This fixes https://github.com/matter-labs/era-test-node/issues/188 and https://github.com/matter-labs/era-test-node/issues/211

feat: Implement web3_clientVersion

---

Cargo.lock
Cargo.toml
src/formatter.rs
src/node/in_memory.rs
src/observability.rs

* Update events to display indexed topics on new lines
* Update events to display data
* Update the observability formatter to be compact (similar to the way it was before the tracing migration)
* Easier to read when there are more than 2 indexed topics (super common)
* This was not being displayed
* Better user experience during demos as it reduces the amount of text on the screen or in the logs
Starting a node (with new observability formatter)
Events are now updated
BEFORE
AFTER
Examples of more events:
* I know that I'm not parsing the ABI properly to display the data as a string... but it's better than nothing and we can have that as an easy GitHub Issue once this is merged

feat: Update event formatter and observability formatter

---

SUPPORTED_APIS.md
e2e-tests/helpers/constants.ts
src/main.rs

* Add rich accounts with mnemonic phrases
* Updated `SUPPORTED_APIS`
* Test suites commonly rely on mnemonic phrases with things like foundry
* Support is updated for `eth_sendTransaction`
This is what `era_test_node run` now looks like:
E2E tests still pass 👍 
* I'm keeping the legacy rich wallets so that everything is still backwards compatible... I'm just not printing them out to the console

chore: Add Rich Accounts with mnemonic phrases

---

src/fork.rs

* Fixed a bug with incorrect marking of initial writes, which resulted in larger pubdata estimation when replaying transactions
* Each write to storage means, that we have to charge user some pubdata, to cover the cost of writing this data down to L1. But the costs are a little bit lower, if we had written this key in the past (we charge 32 bytes for the first write of the key, and 4 bytes for subsequents writes)
* This improves the gas computation correctness - which is important when replaying the transactions that use close to their gas limit (like the one below - 0xb0f917b869172db5123e7a63bc0f9ef4fa7498f1db34d094250087578136fde6)
We are still around 100 gas off, but before this fix, the delta was over 50k

fix: Fix issue with incorrect recognition of initial writes

---

src/formatter.rs
src/node/in_memory.rs
src/node/mod.rs
src/node/storage_logs.rs

* Display detailed information on how many pubdata bytes does each write cost
* added "paid" option to --show-storage-logs to see only the writes that cost pubdata
* The cost of pubdata is in many cases the highest cost related to the transaction
* with boojum release, we use pubdata compression, so each slot might use between 6 and 64 bytes - so it is important for users to see how much they have to pay - and this would also be a good signal for them to see where they can save.

feat: Added detailed information on amount of pubdata per write

---

.github/CONTRIBUTING.md

- I've found typo in link to developer discussion, this PR fixes the link. Maybe the target [repo](https://github.com/zkSync-Community-Hub/zkync-developers/discussions) should be renamed, because the original typo is in the repository name.
- To keep external resources approachable.
No special evidence.

fix: update typo in link to dev discussion

---

Cargo.lock
Cargo.toml
README.md
docs/rustbook/src/usage/fork.md
docs/rustbook/src/usage/remote-tx.md
docs/rustbook/src/usage/testing.md
src/fork.rs
src/main.rs

* Add support for sepolia testnet
* Update version to `0.0.1-alpha.14`
* As Sepolia is the new testnet for zkSync
* To maintain consistency
```bash
nvillanueva ~/github/matter-labs/era-test-node (main) $ era_test_node fork sepolia-testnet
15:23:50  INFO Creating fork from "https://sepolia.era.zksync.dev:443" L1 block: L1BatchNumber(4520) L2 block: 15631 with timestamp 1703085270, L1 gas price 17153871265 and protocol version: Some(Version19)
15:23:50  INFO Starting network with chain id: L2ChainId(260)
15:23:50  INFO 
15:23:50  INFO Rich Accounts
15:23:50  INFO =============
15:23:53  INFO Account #0: 0xBC989fDe9e54cAd2aB4392Af6dF60f04873A033A (1_000_000_000_000 ETH)
...
```
Replay transaction on Sepolia testnet fork

feat: Add support for sepolia testnet

---

src/bootloader_debug.rs

* Fixed the detailed gas computation - after the most recent release, the bootloader memory layout has changed and it we didn't update it.

fix: Fix the memory position for bootloader debug information

---

Cargo.lock
Cargo.toml
src/fork.rs

* Add missing support for v23, v24, and v25
* Bump version in `cargo.toml` to upcoming release
* This is blocking `./era_test_node fork testnet`
* To match the version in GitHub Releases
Successful forking of testnet
Successful forking of mainnet

fix: add missing version support and increase version in toml

---

e2e-tests/test/zks-apis.test.ts
src/node/eth.rs
src/node/fee_model.rs
src/node/in_memory.rs
src/node/in_memory_ext.rs
src/node/zks.rs
src/testing.rs

Halved `L2_GAS_PRICE` to 25000000 and changed the fee model to match.
Replaying some Sepolia transactions didn't work with the original value.
Both unit and e2e tests pass.

fix: L2 gas price change

---

e2e-tests/test/zks-apis.test.ts
src/bootloader_debug.rs
src/node/in_memory.rs
src/node/zks.rs

* Fix the gas limit being added to itself
* Fix bootloader memory layout (to match the most recent bootloader params)
* Fix mutex usage
* `--show-gas-details=all` was blocked by both bootloader and mutex issues
* double gas limit was blocking the deployment of larger contracts due to going over the block gas limit

fix: double gas limit, bootloader memory layout

---

src/fork.rs
src/main.rs
src/node/in_memory.rs

- Automatically set the L2 fair gas price based on which network we're forking from.
Instead of having the L2 gas base price only as a constant/cli-argument, this PR introduces support for fetching the `l2_fair_gas_price` value within `BlockDetails`. This means that when forking from a network the base price will be adjusted automatically and no manual changing of the constant is necessary.
_Forking from `sepolia-testnet`, the L2 gas price is set to `25_000_000`._
_Forking from `sepolia-testnet`, this time overriding the procured gas price with `--l2-gas-price=50000000`._

feat: procure l2 gas price when forking

---

Cargo.toml

Incremented version from `"0.1.0-alpha.21"` to `"0.1.0-alpha.23"`.
- To have a release that includes [these changes](https://github.com/matter-labs/era-test-node/pull/289)
- Version 22 has already been released

chore: Incremented toml version

---

src/fork.rs
src/node/eth.rs
src/node/in_memory_ext.rs
src/node/zks.rs
src/utils.rs

Make functions implementing `ReadStorage` for `ForkStorage` return `Result::Err` on failure, and call them in preference to the panicking interface.
Showing a network error is preferable to server panic.
Both unit and e2e tests pass.
Unfortunately the `ReadStorage` trait cannot be removed, because it's used by zkSync Era - for a clean solution, it should be updated (so that its methods return `Result`) there.

fix: added errors to internal implementation of ReadStorage

---

src/fork.rs
src/main.rs
src/node/fee_model.rs
src/node/in_memory.rs

- Introduces a new enum `ForkNetwork` encapsulating network local values.
Currently, the scaling gas estimation parameters are hardcoded [here](https://github.com/eqlabs/era-test-node/blob/7a4722fe741009a4a46247438bfa09680572a2dd/src/node/in_memory.rs#L79) and [here](https://github.com/eqlabs/era-test-node/blob/7a4722fe741009a4a46247438bfa09680572a2dd/src/node/in_memory.rs#L85). However, these should actually be dependant on the network we fork from. These values can not yet be fetched from a publicly available source and as such, this PR introduces a temporary measure for hardcoding different gas estimation constants for each valid network source.
1. Running the test node with `cargo run --release fork <NETWORK>`.
2. Sending the following request: 
```bash
curl -X POST -H "Content-Type: …
```

feat: different scaling gas constants based on forked network

---

Cargo.lock
Cargo.toml
e2e-tests/test/hardhat-apis.test.ts
src/node/hardhat.rs
src/node/in_memory.rs
src/node/in_memory_ext.rs
src/utils.rs

Replaced `hardhat_setCode` implementation to not panic on code parsing.
The code argument is user-controlled, and users shouldn't be able to crash the node
just by calling its API. At #252, they're complaining it can happen even accidentally.
Added test:
```
hardhat_setCode
✔ Should set code at an address (279ms)
✔ Should reject invalid code
✔ Should update code with a different smart contract (291ms)
```

fix: hardhat_setCode error handling

---

Cargo.lock
src/fork.rs
src/http_fork_source.rs
src/node/fee_model.rs
src/node/in_memory.rs
src/node/zks.rs
src/testing.rs

- When forking from a network, adds a call to the RPC endpoint grabbing the current `FeeModel` configuration in use by the current protocol version at that network point.
- Currently L2 gas price and L1 gas price is automatically adjusted to appropriate levels, but the rest of the parameters in the fee model is not. This results in some transactions being executable while others are not.
- Closes #303.
Replaying the same transaction (`0xbbcf756e95b3b4024c85e188ce5801470e67b128dde1f95364c99e092ac46109`) on this branch and latest main (`93946cc`):
https://github.com/matter-labs/era-test-node/assets/94441036/296b717d-8a52-42ee-b6ac-0a38d85e15bd
_`feat/dynamic-fee-model-config`_
https://github.com/matter-labs/era-test-node/assets/94441036/51dccad0-1583-46d9-8918-00661d9ea02c
_`main`_

feat: dynamic fee model config

---

e2e-tests/test/eth-apis.test.ts
src/node/eth.rs

Setting `TransactionRequest` `gas` and `gas_price` inside `eth_sendTransaction` API if they weren't set explicitly by caller.
The fields are optional and documented as having "reasonable defaults", but the test node left them at None, leading to transaction failure (as described in https://github.com/matter-labs/era-test-node/issues/278 ).
Added e2e tests:
```
eth_sendTransaction
✔ Should execute with impersonation
✔ Should fail without impersonation
```

fix: send transaction fees

---

SUPPORTED_APIS.md
src/namespaces/hardhat.rs
src/node/hardhat.rs
src/node/in_memory_ext.rs

Added `hardhat_setStorageAt` API.
Fixes https://github.com/matter-labs/era-test-node/issues/276 .
Added `test_set_storage_at`, which passes:
```
test node::in_memory_ext::tests::test_set_storage_at ... ok
```

feat: added hardhat_setStorageAt

---

.github/workflows/e2e.yml
src/main.rs

Makes `era_test_node` treat `run` as the default subcommand.
Ergonomics and L1 compatibility. You can run `anvil` without any arguments, I'd expect `era_test_node` to do the same.

feat: Treat 'run' as default command

---

e2e-tests/test/eth-apis.test.ts
src/node/in_memory.rs

Includes transaction type in the transaction receipts.
Some clients (e.g. `alloy`) expect this information to be present in the receipt.
I've added a test, but also manually checked with `alloy`: before this change getting the tx receipt was failing, but with this change it succeeds.

fix: Include transaction type in the transaction receipt

---

src/fork.rs
src/main.rs
src/node/in_memory.rs

Made the L1 price overridable from command line, in both forking and standalone mode.
Transactions succeed of fail depending on the node fees, and users/developers might want to experiment with that. 
Example (in replay mode):
```
$ ./target/release/era_test_node --show-calls=all --show-outputs --show-vm-details=all --resolve-hashes replay_tx sepolia-testnet 0xadf8319da65e377909e41a4806cb24eb7090cbdaf4521fad5084cfa933ce1849
10:31:45  INFO Creating fork from "https://sepolia.era.zksync.dev:443" L1 block: L1BatchNumber(8961) L2 block: 2386764 with timestamp 1715930527, L1 gas price 157087620156, L2 fair gas price 25000000 and protocol version: Some(Version24)
...
[!] Halt Reason:    virtual machine entered unexpected state. Please contact developers and provide transaction details that …
```

feat: custom l1 price

---

Makefile
src/fork.rs
src/node/in_memory.rs
src/testing.rs
src/utils.rs

- Changes `make lint` so that it runs `clippy` for tests too.
- Fixes existing clippy warnings in test code.
It's harder to work with the project when you see unfixed warnings.
Self-evident.

chore: Run clippy in tests

---

Cargo.lock
Cargo.toml
src/main.rs
src/observability.rs
test_endpoints.http

* Update trace logging to include `multivm`
* Updated the version number to match latest
* This allows for `TRACE` logs to include `debugLog` statements from the `bootloader.yul` code
* For consistency
Running `era_test_node --log trace` and having a simple test, you see the following console/log output:
```text
09:27:07 TRACE Bootloader transaction 0: userProvidedPubdataPrice: 50000
09:27:07 TRACE Bootloader transaction 0: gasPerPubdata: 50000
09:27:07 TRACE Bootloader transaction 0: txTotalGasLimit 80000000
09:27:07 TRACE Bootloader transaction 0: requiredOverhead 10000
09:27:07 TRACE Bootloader transaction 0: operatorOverheadForTransaction 10000
09:27:07 TRACE Bootloader transaction 0: gas() 4294953925
09:27:07 TRACE Bootloader transaction 0: gasToProvide 79975930
```

fix: update trace logging to include bootloader

---

Cargo.lock
Cargo.toml
src/main.rs
src/observability.rs

* Fix log filter to work with multiple targets
* Remove `multivm` from log filter
* Update version number for upcoming release
* Multiple targets were not having the `=info` log level applied as expected on start-up, so TRACE logs were showing for `multivm` target
* Warning logs are being thrown with an un-actionable message of `0x function_selector` which is confusing and could have end users believe that something is wrong when there's not
* Expect to release `0.1.0-alpha.25` today
Running `era_test_node` now only have `era_test_node=info` logs:
```bash
$ era_test_node 
14:32:46  INFO Starting network with chain id: L2ChainId(260)
14:32:46  INFO 
14:32:46  INFO Rich Accounts
14:32:46  INFO =============
14:32:46  INFO Account #0: 0xBC989fDe9e54cAd2aB4392Af6dF60f04873A033A …
```

fix: hide multivm log warnings and traces

---

src/node/eth.rs

Changes transaction index from 1 to 0 in tx receipt.
Transaction indices should start from 0 ([example](https://etherscan.io/tx/0x0439cab7af5e6abbc572eafdc58ef65d832a7dcb2f3dcc36ab2182bc77f43ca1)).
From link above:

fix: Set transaction index to 0 in tx receipt

---

README.md

* Fixing the In Memory Node link to our docs
* The old link was 404

fix: update link on README.md

---

Cargo.lock
Cargo.toml
src/cache.rs
src/fork.rs
src/http_fork_source.rs
src/node/eth.rs
src/node/fee_model.rs
src/node/in_memory.rs
src/node/in_memory_ext.rs
src/node/zks.rs
src/testing.rs
src/utils.rs

+ bump `zksync era` dependencies version
+ new get_block_gas_details in `fork.rs` to extract l1 batch gas info.
+ modify `create_l1_batch_env` to construct `BatchFeeInput` from values taken from l1 batch details, if memory node is running in fork mode.
Context: successful txs from fork fails while replaying them with node. 
This is caused by wrong gas/fee values stored in `fee_input_provider` that are used to calculate tx cost.

fix: Use actual replayed tx's  gas and pubdata prices to replay tx.

---

src/fork.rs
src/main.rs
src/node/eth.rs
src/node/zks.rs

Replaced calls to unwrap & expect in `from_network` and `from_network_tx` by explicit errors.
Improved reporting, not panicking on invalid inputs.
Tests pass.

fix: returning errors from from_network and from_network_tx

---

e2e-tests/test/hardhat-apis.test.ts
src/namespaces/hardhat.rs
src/node/hardhat.rs
src/node/in_memory_ext.rs

Changed `hardhat_setCode` code parameter type to string encoding of a hex number.
Fixes https://github.com/matter-labs/era-test-node/issues/325 .
```
$ mocha test/helpers/setCode.ts 
setCode
✔ should allow setting the code of a given address (115ms)
accepted parameter types for code
✔ should not accept strings that are not 0x-prefixed
✔ should not accept non-hex strings
3 passing (525ms)
```
Note that the hardhat testsuite had been modified to pass the test: its original sample code doesn't pass test node checks.

fix: changed hardhat_setCode code type

---

src/fork.rs
src/main.rs

Replaced calls to unwrap & panic in is_write_initial_internal, fork_network_and_client, get_earlier_transactions_in_same_block and get_block_gas_details by explicit errors.
Improved reporting, not panicking on invalid inputs.
Tests pass.

fix: returning errors from fork handling

---

SUPPORTED_APIS.md
e2e-tests/test/anvil-apis.test.ts
e2e-tests/test/evm-apis.test.ts
e2e-tests/test/hardhat-apis.test.ts
e2e-tests/test/main.test.ts
e2e-tests/test/zks-apis.test.ts
src/main.rs
src/namespaces/anvil.rs
src/namespaces/evm.rs
src/namespaces/mod.rs
src/node/anvil.rs
src/node/evm.rs
src/node/mod.rs

Added `evm_setAccountNonce`, `anvil_setNonce`, `anvil_impersonateAccount`, `anvil_stopImpersonatingAccount`, `anvil_mine`, `anvil_reset`, `anvil_setBalance`, `anvil_setCode` and `anvil_setStorageAt` as aliases to the corresponding `hardhat_*` methods.
Implements https://github.com/matter-labs/era-test-node/issues/160 .
Extended e2e tests, which pass.

feat: anvil API

---

src/config/mod.rs
src/fork.rs
src/node/in_memory.rs

* Gas estimation logic for forks now uses the block detail values when the node starts
* `max_gas` during transaction validation is increased from `u32::MAX` to `u64::MAX`
* Previously, every transaction would attempt to grab the block details of the current miniblock. However, `era_test_node` can mine blocks _much_ faster than Sepolia Testnet, so sometimes it would require block details for a block that doesn't exist yet.
* During the `1.5.0` upgrade, [the gas limit of ZKsync was upgraded from `u32` to `u64`](https://github.com/matter-labs/zksync-era/commit/56dc049993d673635e55b545962bf4f6d4f32739). This check was missed in the updates for `era-test-node`
Forking sepolia and running a transaction still works
* This fixes #326

fix: Update gas estimation logic for forks

---

Cargo.lock
Cargo.toml
SUPPORTED_APIS.md
e2e-tests/test/anvil-apis.test.ts
e2e-tests/test/evm-apis.test.ts
e2e-tests/test/main.test.ts
e2e-tests/test/zks-apis.test.ts
src/config/mod.rs
src/constants.rs
src/fork.rs
src/lib.rs
src/main.rs
src/namespaces/anvil.rs
src/namespaces/evm.rs
src/namespaces/mod.rs
src/node/anvil.rs
src/node/evm.rs
src/node/in_memory.rs
src/node/in_memory_ext.rs
src/node/mod.rs
src/node/zks.rs
src/system_contracts.rs
src/testing.rs

Fix tests after gas change
Because 30 tests fail

chore: fix tests after the gas changes

---

src/resolver.rs

* Update the endpoint for resolving hashes to `api.openchain.xyz`
* The previous website is no longer available (`https://sig.eth.samczsun.com/api/v1/signatures`)

fix: Resolve hashes now uses the new openchain.xyz endpoint

---

src/cache.rs
src/resolver.rs

* Add persistent cache for OpenChain requests
* To speed up local debugging, as restarting `era_test_node` would clear the previous cache
BEFORE (tests ran against `era_test_node -d` in 48 seconds):
AFTER (tests ran against `era_test_node -d` in 7 seconds):

feat: Add persistent cache to OpenChain hash resolving requests

---

SUPPORTED_APIS.md
e2e-tests/test/zks-apis.test.ts
src/formatter.rs
src/namespaces/zks.rs
src/node/zks.rs
test_endpoints.http

* Add support for `zks_getBaseTokenL1Address`
* Add gas used per call in the stack
* Added/fixed `SUPPORTED_APIS.md` for `hardhat_reset`
* The updated Portal will not work with In-Memory Node without this endpoint
* Having the diff gas used within the stack is useful instead of having to do mental math
* Formatting of the table looked weird and we should include `curl` snippets for these commands for users to easily reference
Using the `zks_getbaseTokenL1Address` endpoint
The new gas usage diff within the call stack of `era_test_node -d`

feat: Add support for zks_getBaseTokenL1Address. Add gas used per call in the stack

---

.github/workflows/release.yml
Cross.toml

* Suppresses warnings that are treated as errors in cross installation and usage 
* Bump gcc dependencies for x86 cross container for `aws-lc-sys` crate
* Release pipeline was broken as a result of cross installation failing to be installed. See:  https://github.com/matter-labs/era-test-node/actions/runs/11057024685/job/30719919478
* Building will fail with `error: failed to run custom build command for aws-lc-sys v0.21.2` using old gcc dep in cross-containers building for x86 target
- Test release on forked repo: https://github.com/dutterbutter/era-test-node/actions/runs/11071741595

fix: fixes release pipeline due bump in rust version

---

docs/rustbook/src/usage/fork.md
src/config/cli.rs
src/fork.rs
src/main.rs
src/node/in_memory.rs
src/node/zks.rs
src/testing.rs

* Update so forked networks chainID is used, is overridden if explicitly set `--chain-id`
* Rename `fork-at` to fork-block-number`
* Updates tests accordingly
* ChainID when forking a network was still `260` 
* Renames `fork-at` to reflect anvil `fork-block-number` 
* Supports PR for alloy-zksync: https://github.com/popzxc/alloy-zksync/pull/11
**BEFORE:**
**AFTER:**

chore(refactor): update so forked networks chainID is used and rename `fork-at` to fork-block-number`

---

src/config/cli.rs

* Fix typo in arg name `dev-system-contracts` to `dev_system_contracts`
* `emulate_evm` arg has a required defined for `dev-system-contracts` which leads to the following error when run via `era_test_node run`:
```
Command era_test_node: Argument or group 'dev-system-contracts' specified in 'requires*' for 'emulate_evm' does not exist
```

fix: arg required name for emulate_evm

---

src/config/cli.rs

* Removes erroneous `requires("fork")`
* The group `fork` does not exist and panics in debug builds due to clap's `debug_asserts`. Additionally the args are now contained within the `fork` subcommand so requires is redundant.
* Similar to https://github.com/matter-labs/era-test-node/pull/379
Tested locally

fix: remove erroneous clap::requires

---

.gitmodules
spec-tests/tests/lib.rs

This PR creates a git submodule that points to https://github.com/ethereum/execution-apis (official ETH JSONRPC spec). Building it produces `openrpc.json` file that we rely on for spec tests.
Closes #375 
On the road of making spec tests enforceable in CI

feat(spec-tests): add execution-apis submodule

---

Cargo.lock
Cargo.toml

* Bump version to `0.1.0-alpha.32`
* For release

chore: bump version for release

---

e2e-tests/test/evm-apis.test.ts
src/node/config_api.rs
src/node/eth.rs
src/node/in_memory.rs
src/node/in_memory_ext.rs
src/node/mod.rs
src/node/time.rs
src/utils.rs

Makes time management less rigid by moving the logic into its own component.
Closes #386 
Some flows depend on getting unique timestamps (e.g. new block, new batch, etc) and they really shouldn't hold a mutable reference to the node's internal state all the time.

refactor: move time management into its own component

---

src/namespaces/anvil.rs
src/namespaces/hardhat.rs
src/node/anvil.rs
src/node/eth.rs
src/node/hardhat.rs
src/node/in_memory.rs
src/node/in_memory_ext.rs
src/testing.rs
src/utils.rs

Hefty refactoring of block sealing into its own logical layer on top of tx execution. This opens up a way to support several txs per block and dynamic block sealing in general. This PR also gets rid of all the ad-hoc empty block logic and instead replaces them with `seal_block([])`. Making us have a centralized place where all the blocks are created and thus this PR closes #358 
The code is still pretty messy but I want to gradually improve it as I suspect many things here will go into separate subcomponents (e.g. `BlockSealer`, `BatchSealer` etc)
Entangled sealing logic made it very hard to make it customizable for #362

refactor: separate block sealing logic from executing txs

---

Makefile
src/node/eth.rs
src/node/impersonate.rs
src/node/in_memory.rs
src/node/in_memory_ext.rs
src/node/mod.rs

Closes #390 (see for more motivation)
Less dependence on the `InMemoryNodeInner` state, needed for #362

refactor: move impersonation management into its own component

---

src/config/cli.rs
src/config/mod.rs
src/main.rs

* Added a new CLI option `--config-out` to specify an output file for JSON configuration.  
* Introduced a `config_out` field in the `TestNodeConfig` struct to handle output file specification.  
* Updated configuration handling with new methods: `as_json` for JSON conversion and `set_config_out` for setting the output file.  
* Updated the `print` method in `TestNodeConfig` to write configuration to the specified JSON file if `config_out` is set.  
* Aligns with Anvil CLI options
* To provide users with the ability to export configuration settings as a JSON file for easier debugging and external processing.  
Usage examples:  
1. Exporting configuration during a `fork` command:  
```bash
./target/release/era_test_node --config-out text.json fork --network mainnet
```  
2. Exporting …

feat: adds config-out cli option

---

e2e-tests/test/eth-apis.test.ts
src/config/cli.rs
src/config/constants.rs
src/main.rs
src/node/debug.rs
src/node/eth.rs
src/node/in_memory.rs
src/testing.rs

* Fixes issue with `--balance` not being used correctly
* Users should be able to specify balance (e.g. `./target/release/era_test_node --accounts 15 --balance 300 run`

fix: fix issue with balance usage

---

SUPPORTED_APIS.md
e2e-tests/test/anvil-apis.test.ts
e2e-tests/test/evm-apis.test.ts
src/namespaces/anvil.rs
src/namespaces/evm.rs
src/node/anvil.rs
src/node/evm.rs
src/node/in_memory_ext.rs
src/utils.rs

Closes #420
This PR aligns `evm_` time API closer to the industry standard (agnostic on whether timestamps are plain numbers or hexified). And adds corresponding `anvil_` bindings for the same functionality.

feat: add `anvil_setTime`, `anvil_increaseTime`, `anvil_setNextBlockTimestamp`

---

src/node/in_memory.rs

Reverts to using `vm.push_transaction` that was changed in https://github.com/matter-labs/era-test-node/pull/349/files#diff-1d93f40c8381a01bae127f34171f5bbd3cef45d00038102a2fbcdd9ad4d7fdfdR1356
* Some intermittent failures were observed with retrieving compressed bytecodes with the last upstream merge. https://github.com/matter-labs/zksync-era/pull/3126 was merged to simplify this process.
Tests pass

fix: obtain compressed bytecodes from vm.push_transction

---

SUPPORTED_APIS.md
e2e-tests/test/anvil-apis.test.ts
src/namespaces/anvil.rs
src/node/anvil.rs
src/node/config_api.rs
src/node/in_memory.rs
src/node/in_memory_ext.rs
src/observability.rs

Closes #433 
This PR does a minor refactoring of `Observability` + its usage in `InMemoryNode` while adding the ability to disable logging entirely by setting env filter to `off`. As a consequence of that we need to store last used directives so we can recover them when user re-enables the logs. The exact cross-interaction with `config_` methods is unspecified as `anvil` does not support that namespace, so I went with made the most sense to me.

feat: add `anvil_setLoggingEnabled`

---

SUPPORTED_APIS.md
src/namespaces/anvil.rs
src/node/anvil.rs

Closes #434
This PR explicitly marks this method as unimplemented by design (see issue for the discussion on why).
Transparency about its status

feat: add `anvil_setMinGasPrice` as an unimplemented method

---

src/config/cli.rs
src/config/mod.rs
src/main.rs

* adds `fork-transaction-hash` 
* rename `network` to `fork-url`
* adds update methods for fork configuration to TestNodeConfig impl
* Anvil CLI parity 
**Usage:**
```
./target/release/era_test_node fork --fork-url mainnet --fork-transaction-hash 0xd92d802ba395e3e6db0c6def7f88e5828aa466118dc87d3b96a9fef718b851d5
```

feat: adds `fork-transaction-hash` and rename `network` to `fork-url`

---

src/config/cli.rs
src/config/mod.rs
src/main.rs

* Fixes use of configuring gas params using `run` and `fork` instances
* Adds alias for l2-gas-price for `gas-price` 
* Allows for overriding gas params for `run` and `fork` instances
* Aligns with anvil 
**Example with random values:**
`./target/release/era_test_node --l1-gas-price 1000000 --l2-gas-price 50 --l1-pubdata-price 1000 --limit-scale-factor 1.5 fork --fork-url mainnet`

fix: fixes gas params usage and add alias 

---

src/config/cli.rs
src/config/constants.rs
src/config/mod.rs
src/node/eth.rs
src/node/in_memory.rs
src/utils.rs

* adds init and timestamp genesis cli params
* Anvil-zksync parity 
genesis.json:
```json
{
"hash": null,
"parent_hash": null,
"block_number": 0,
"timestamp": 1638316800,
"l1_batch_env": {
"previous_batch_hash": null,
"number": 0,
"timestamp": 1732653220,
"fee_input": {
"PubdataIndependent": {
"l1_gas_price": 1,
"fair_l2_gas_price": 2,
"fair_pubdata_price": 1000000000000000
}
},
"fee_account": "0x0000000000000000000000000000000000000000",
"enforced_base_fee": null,
"first_l2_block": {
"number": 0,
"timestamp": 1638316800,
"prev_block_hash": "0x0000000000000000000000000000000000000000000000000000000000000000",
"max_virtual_blocks_to_create": 0
}
},
"transactions": [], …
```

feat: adds init and timestamp genesis cli params

---

SUPPORTED_APIS.md
e2e-tests/test/anvil-apis.test.ts
src/namespaces/anvil.rs
src/node/anvil.rs
src/node/block_producer.rs
src/node/config_api.rs
src/node/debug.rs
src/node/eth.rs
src/node/in_memory.rs
src/node/in_memory_ext.rs
src/node/time.rs
src/node/zks.rs

Closes #423 
This kind of snowballed out of control as I had to refactor time management in a way that unties it from relying on `+1` everywhere. The gist is that I introduced two new traits:
* `TimeRead` to represent shared read-only view on time
* `TimeExclusive` to represent exclusive writeable view on time
Sealing blocks requires a `TimeExclusive` instance to be passed now and we have some flexibility in what we can pass. This fixes a few TOCTOU bugs that we used to have (we rely on clock not progressing between us constructing the new block and applying it, which was not always the case before but it is not with `TimeExclusive`). This also made `mine_blocks` more robust as it enforces the provided offsets now.
Additionally this PR removes time from snapshot state (See …

feat: add `anvil_{set,remove}BlockTimestampInterval`

---

SUPPORTED_APIS.md
e2e-tests-rust/src/lib.rs
e2e-tests-rust/tests/lib.rs
spec-tests/Cargo.lock
spec-tests/Cargo.toml
src/namespaces/anvil.rs
src/node/anvil.rs
src/node/in_memory_ext.rs
src/node/pool.rs

Closes #417 
The logic is fairly straightforward for now, the complexity will arrive once we start building dependency graphs between transactions in the mempool. Then deleting one manually can cause a cascading effect resulting in more deleted transactions.

feat: add `anvil_` pool manipulation methods

---

SUPPORTED_APIS.md
e2e-tests/test/anvil-apis.test.ts
src/namespaces/anvil.rs
src/node/anvil.rs
src/node/eth.rs
src/node/fee_model.rs
src/node/in_memory.rs
src/node/in_memory_ext.rs
src/node/zks.rs

Closes #449 
Fee management is a big mess right now and IMHO we should invest some time into aligning it with core. This PR introduces support for `anvil_setNextBlockBaseFeePerGas` with minimal invasion for now.

feat: add `anvil_setNextBlockBaseFeePerGas`

---

SUPPORTED_APIS.md
src/fork.rs
src/namespaces/anvil.rs
src/node/anvil.rs
src/node/in_memory_ext.rs

Closes #448
We don't have any tests for forks right now and we should discuss what shape they should take as depending on external services is generally not a great idea for tests. For now I tested this manually (changed from https://mainnet.era.zksync.io to https://1rpc.io/zksync2-era), seems to work as expected.

feat: add `anvil_setRpcUrl`

---

SUPPORTED_APIS.md
e2e-tests-rust/Cargo.lock
e2e-tests-rust/Cargo.toml
e2e-tests-rust/src/lib.rs
e2e-tests-rust/tests/lib.rs
src/namespaces/anvil.rs
src/namespaces/mod.rs
src/node/anvil.rs
src/node/evm.rs
src/node/in_memory.rs
src/node/in_memory_ext.rs

Closes #454
The RPC is fairly straightforward but testing it required me to go on a rabbit hole that uncovered that alloy-zksync can't query transactions or hydrated blocks right now. https://github.com/popzxc/alloy-zksync/issues/29 is what I arrived at while working on this, e2e-tests-rust has been updated to use that branch.

feat: add `anvil_mine_detailed`

---

SUPPORTED_APIS.md
e2e-tests-rust/Cargo.lock
e2e-tests-rust/Cargo.toml
e2e-tests-rust/src/lib.rs
e2e-tests-rust/tests/lib.rs
src/deps/mod.rs
src/deps/system_contracts.rs
src/namespaces/anvil.rs
src/namespaces/mod.rs
src/node/anvil.rs
src/node/debug.rs
src/node/eth.rs
src/node/evm.rs
src/node/in_memory.rs
src/node/in_memory_ext.rs
src/node/zks.rs
src/system_contracts.rs

* Minor refactorings to reduce boilerplate and unnecessary locking
* Makes all manual mining methods take transactions from the mempool when they can
Closes #404 
Correct behavior expected by users

fix: make manual mining produce non-empty blocks

---

src/config/cli.rs
src/config/constants.rs
src/config/mod.rs
src/main.rs
src/node/zks.rs

* Fix issue with gas params always using default values
* Fix issue with never using forked gas params due to default values superseding 
* Remove unwanted log
* Respects offline usage
* Should use most accurate gas params 
* Log shouldnt be there
* Offline was not accounted for in config 

fix: fix issue with gas params

---

crates/cli/src/bytecode_override.rs
crates/cli/src/main.rs
crates/core/src/fork.rs
crates/core/src/node/anvil.rs
crates/core/src/node/block_producer.rs
crates/core/src/node/config_api.rs
crates/core/src/node/debug.rs
crates/core/src/node/eth.rs
crates/core/src/node/evm.rs
crates/core/src/node/hardhat.rs
crates/core/src/node/in_memory.rs
crates/core/src/node/in_memory_ext.rs
crates/core/src/node/net.rs
crates/core/src/node/web3.rs
crates/core/src/node/zks.rs
crates/core/src/testing.rs

Closes #493 
This generic hasn't been useful for quite some time (effectively does nothing as its functionality was moved to `fork_source: Box<dyn ForkSource + Send + Sync>` in `ForkDetails`). This is a good opportunity to simplify our code as this generic appears all over the place without being needed.
Dead code

refactor: remove `S` generic from `InMemoryNode` and `ForkStorage`

---

SUPPORTED_APIS.md
crates/cli/src/cli.rs
crates/cli/src/main.rs
crates/config/src/config.rs
e2e-tests-rust/src/lib.rs
e2e-tests-rust/src/provider/mod.rs
e2e-tests-rust/src/provider/testing.rs
e2e-tests-rust/src/utils.rs
e2e-tests-rust/tests/lib.rs

Added `--allow-origin` cli option;
Added `--no-cors` cli option;
Feature parity with anvil;

feat: add cli options for server configuration

---

crates/core/src/node/eth.rs
crates/core/src/node/in_memory.rs
e2e-tests-rust/tests/lib.rs

- Properly set transaction index.
- Since block can have many transactions using `0` as tx index is no longer valid.
Closes https://github.com/matter-labs/anvil-zksync/issues/498

fix: properly set transaction index

---

crates/core/src/console_log.rs

- Do not print `=== Console logs` title unless there are some logs to print.

fix: don't print console logs title when no console logs printed

---

crates/cli/src/cli.rs
crates/cli/src/main.rs
crates/config/src/config.rs
crates/config/src/types/mod.rs
crates/config/src/types/transaction_order.rs
crates/core/src/node/in_memory.rs
crates/core/src/node/in_memory_ext.rs
crates/core/src/node/pool.rs
crates/core/src/node/sealer.rs
e2e-tests-rust/src/provider/testing.rs
e2e-tests-rust/tests/lib.rs

- Added CLI param `--order` for transactions order in mempool.
- Added `fees` transactions order option, sorts transactions by `max_fee_per_gas`.
- FIFO is still the default option to reflect mainnet.
Feature parity with anvil.

feat: fees transactions order in mempool

---

.github/workflows/release.yml

Adds binary attestations for releases (for now, only for binaries).
See [action](https://github.com/actions/attest-build-provenance)
Allows to verify the validity of the binary. See [gh attestation verify](https://cli.github.com/manual/gh_attestation_verify)

feat: Add binary attestation

---

crates/api_server/src/server.rs
crates/cli/src/main.rs

When we spawn the node with port = 0, it means that the system will allocate any free port for us.
However currently we will print that the node runs on port 0 (which is incorrect).
This PR fixes it.

fix: Print correct port for spawned server

---

Cross.toml

* Updates Cross.toml to add libssl-dev to cross container
* Required to build on `aarch64-unknown-linux-gnu`

chore: add libssl-dev to cross container

---

.github/workflows/release.yml

Fixes the attestation path
Binary's path depends on the target triple and is moved in the release pipeline

chore: fix release attestation

---

scripts/install.sh

* Fixes install script for apple as the arch is detected as `i386` 
* Fixes here as well: https://github.com/matter-labs/foundry-zksync/pull/820
* Closes #519 
* Properly makes use of x86 binary

fix: fixes install script for apple x86

---

scripts/refresh_contracts.sh

* Fixes the artifact destination path in `refresh_contracts.sh`
* Old path was still being used post crate-split.
Tested locally

fix: destination path in refresh contracts script

---

.github/workflows/checks.yaml
.github/workflows/e2e-docker.yml
.github/workflows/e2e-rust.yml
.github/workflows/e2e.yml
.github/workflows/release.yml
.github/workflows/spec.yml
Makefile
crates/api_server/src/server.rs
crates/cli/src/main.rs
crates/core/src/node/inner/in_memory_inner.rs
e2e-tests-rust/Cargo.lock
e2e-tests-rust/Cargo.toml
e2e-tests-rust/src/lib.rs
e2e-tests-rust/tests/lib.rs

* fixes: anvil-zksync able to start even if the port is busy, Closes #512 
* Bump CI versions for upload / download artifacts. See:
```
deprecated version of `actions/download-artifact: v3`. Learn more: https://github.blog/changelog/2024-04-16-deprecation-notice-v3-of-the-artifact-actions/
```
* Should be able to use fallback port if busy without panic

fix: anvil-zksync able to start even if the port is busy

---

crates/api_decl/src/namespaces/zkos.rs
crates/api_server/src/impls/zkos.rs

* changed witness to return data as hex string - to make it easier to pass to downstream tools

feat: [zkos] change witness from Vec<u8> to hex string

---

crates/cli/src/main.rs
crates/core/src/node/in_memory.rs

* Spawn `NodeExecutor` before applying replay transactions in `main.rs`
* Closes #543 
* When making use of `replay_tx` we were sending a command over a channel and then waiting for a response but the `NodeExecutor` had not been started yet, so it never read that command or sent back a reply which caused the node to hang.
```
./target/release/anvil-zksync --reset-cache=true --cache=none replay_tx --fork-url mainnet 0x4f8a6c93fee26a3dd01ee0c92f0adeb78960ba36b20b24de61392983234e60dd
20:40:41  INFO 
20:40:41  INFO Validating 0x6dbfcea28c98a8ee26a3688436c29be3579f70adb90ee801eaee976e7b364996
20:40:41  INFO Executing 0x6dbfcea28c98a8ee26a3688436c29be3579f70adb90ee801eaee976e7b364996 …
```

fix: Spawn `NodeExecutor` before applying replay transactions

---

.github/workflows/check-pr-title.yml
crates/cli/src/main.rs

This PR changes behaviour of `anvil-zksync fork --fork-url <url> --fork-transaction-hash <hash>`:
**Before**: fork is initialized at the parent of the block containing provided tx hash, earlier transactions **are not** replayed
**Now**: fork is initialized at the parent of the block containing provided tx hash, earlier transactions **are** replayed
This better aligns to what I would expect to happen but admittedly this is a breaking change

feat(cli)!: replay transactions when forking at a tx hash

---

Cargo.lock
Cargo.toml
crates/core/Cargo.toml
crates/core/src/console_log.rs
crates/core/src/node/debug.rs
crates/core/src/node/inner/in_memory_inner.rs
crates/core/src/utils.rs
e2e-tests-rust/Cargo.lock

* updates unmaintained deps to alloy alternatives
* Dont want unmaintained deps
Closes #507 

chore: updates unmaintained deps to alloy alternatives

---

Cargo.lock
Cargo.toml
crates/cli/Cargo.toml
crates/cli/src/cli.rs
crates/config/Cargo.toml
crates/config/src/config.rs
crates/config/src/types/account_generator.rs
crates/core/Cargo.toml
crates/core/src/console_log.rs
crates/core/src/node/debug.rs
crates/core/src/node/inner/in_memory_inner.rs
crates/core/src/utils.rs
e2e-tests-rust/Cargo.lock
e2e-tests-rust/Cargo.toml

Avoid 2 different sets of alloy in our dependencies
**UPD**: Actually, I have just realized that depending on alloy-zksync isn't even necessary so this PR gets rid of it (we still use it in e2e tests though).
Less things to compile

chore: sync `alloy-zksync` version with base `alloy` crate

---

.github/workflows/release-please.yml

Update release token.
To enable CI in release PRs.

chore: update release token to enable ci in release PRs

---

crates/cli/src/cli.rs

* adds abstract and abstract-testnet to named fork options
* Tired of having to type rpc url entirely 

feat: adds abstract and abstract-testnet to named fork options

---

crates/cli/src/main.rs

* refrain from starting server during tx replay
* Closes #521 
```
./target/release/anvil-zksync replay_tx --fork-url https://api.testnet.abs.xyz 0xce7b0578808283cad26cba971e1ab814e48aeb20041b925691d2b484f3b06ae7
❌ [FAILED] Hash: 0xce7b0578808283cad26cba971e1ab814e48aeb20041b925691d2b484f3b06ae7
Initiator: 0xe0a5b54fd2f4628250294415c9f49ceed725e722
Payer: 0xe0a5b54fd2f4628250294415c9f49ceed725e722
Gas Limit: 450_000 | Used: 262_460 | Refunded: 187_540
Paid: 0.0000065615 ETH (262460 gas * 0.02500000 gwei)
Refunded: 0.0000046885 ETH
```

fix: refrain from starting server during tx replay

---

.github/workflows/release.yml

ci: fix linux aarch64 builds

---

.github/workflows/cargo-license.yaml
Cargo.lock
Cargo.toml
crates/cli/Cargo.toml
crates/cli/src/cli.rs
crates/core/Cargo.toml
crates/core/src/cache.rs
crates/l1_sidecar/Cargo.toml
crates/l1_sidecar/src/anvil.rs
deny.toml

This PR migrates from tempdir (unmaintaned) to tempfile and enforces cargo-deny check that forbids openssl

chore: add cargo-deny

---

.github/workflows/release.yml

* use dynamic glibc linkage for linux executables
* To prevent issues with statically linked glibc.
* Ubuntu 20.04 is deprecated now.

build: use dynamic glibc linkage for linux executables

---

crates/api_server/src/impls/net.rs

Fixes #574 (specifically https://github.com/matter-labs/anvil-zksync/issues/574#issuecomment-2680328188)

fix: block `net_version` on a separate runtime

---

.dockerignore
Dockerfile

Ditto, temporary measure before 1.28.1/1.28.2 makes it into `cargo-chef`'s latest Docker image
CI is borked

chore: fix Docker builds on rustup 1.28.0

---

crates/core/src/node/in_memory_ext.rs
crates/core/src/node/inner/node_executor.rs

Makes fee enforcement go through `NodeExecutor`. Once we allow multiple blocks per batch (see https://github.com/matter-labs/anvil-zksync/issues/363) it won't make sense to be able to change base fee on the fly without regard for `NodeExecutor` as you have to force seal a batch to change base fee.
Future proofing for the upcoming `BatchExecutor` major refactoring

refactor: enforce block base fee through `NodeExecutor`

---

crates/core/src/node/eth.rs

Spent half a day yesterday debugging why `eth_sendTransaction` produces transactions with hash differing between Rust and EVM bootloader. Apparently `sig.v=0` (not 27) is the correct behavior as bootloader subtracts 27 from `v` and uses the result for hash calculation ([source](https://github.com/matter-labs/era-contracts/blob/main/system-contracts/contracts/BootloaderUtilities.sol#L299)).
Important for https://github.com/matter-labs/anvil-zksync/pull/600 as difference in tx hash between bootloader and multivm can produce weird side effects.

fix: make `eth_sendTransaction` construct proper transactions

---

.github/workflows/e2e-rust.yml
Cargo.lock
Cargo.toml
crates/cli/src/cli.rs
crates/cli/src/main.rs
crates/config/src/config.rs
crates/l1_sidecar/Cargo.toml
crates/l1_sidecar/src/anvil.rs
crates/l1_sidecar/src/lib.rs
e2e-tests-rust/Cargo.lock
e2e-tests-rust/Cargo.toml
e2e-tests-rust/src/lib.rs
e2e-tests-rust/tests/l1.rs

This PR:
* Renames `--with-l1 [--l1-port <port>]` to `--spawn-l1 [<port>:8012]` and makes it rely on host-installed `anvil` thus removing `foundry` from our dependencies
* Adds `--external-l1 <address>` that assumes caller has started anvil themselves at the provided address
* Migrates e2e tests to use external L1 thus avoiding zombie processes problem (see https://github.com/popzxc/alloy-zksync/pull/47)
More flexibility in how to run anvil-zksync with L1

feat: support both spawned and external L1s

---

Cargo.lock
Cargo.toml
crates/l1_sidecar/src/anvil.rs
crates/l1_sidecar/src/l1_sender.rs
crates/l1_sidecar/src/l1_watcher.rs
e2e-tests-rust/Cargo.lock
e2e-tests-rust/Cargo.toml
e2e-tests-rust/src/contracts/mod.rs
e2e-tests-rust/src/headers_inspector.rs
e2e-tests-rust/src/lib.rs
e2e-tests-rust/src/provider/anvil_zksync.rs
e2e-tests-rust/src/provider/mod.rs
e2e-tests-rust/src/provider/testing.rs
e2e-tests-rust/src/test_contracts/mod.rs
e2e-tests-rust/tests/l1.rs
e2e-tests-rust/tests/lib.rs

This PR:
* Migrates anvil-zksync + e2e tests to alloy 0.12.x
* Makes e2e initialization a bit cleaner by implementing builder pattern for `TestingProvider`
* Renames `TestingProvider` to `AnvilZksyncTester` and makes it hold both `l1_provider` (optional) and `l2_provider`
Keeping up with alloy development + a bunch of long overdue refactorings

chore: upgrade alloy to 0.12.x

---

crates/l1_sidecar/src/anvil.rs

Noticed that we do not allow `anvil 1.0.0-nightly` so I relaxed constraints
Current nightly anvil releases still use `1.0.0` as the base (which is weird given that 1.0.0 has been released already)

fix: allow wider `anvil` versions

---

crates/cli/src/main.rs
crates/core/src/node/in_memory.rs
crates/core/src/node/in_memory_ext.rs
crates/core/src/node/inner/fork.rs

There is no functional restriction on why we can't replay L1 txs (or even upgrade txs) from fork. This PR ensures this flow is supported.
Useful for debugging L1 transactions from testnet/mainnet

feat: support replay of L1 and upgrade transactions

---

crates/core/src/node/inner/in_memory_inner.rs

* Convert MAX_VM_PUBDATA_PER_BATCH (761,856) from usize to u32 using `as` cast, which is safe since the constant is statically computed as 6 blobs * (31 * 4096) bytes and well within u32 bounds.
* `deranged` dependency update from 0.4.0 to 0.4.1 from Upstream Foundry isn't possible without this conversion for the type infer. 

fix: usize to u32 conversion for pubdata limit

---

Cargo.lock
e2e-tests-rust/src/contracts/mod.rs

Fix new compilation warnings and upgrade tokio to resolve cargo deny error
CI is red

chore: resolve new `rustc 1.86.0` warnings + fix cargo deny

---

crates/core/src/node/eth.rs
crates/core/src/node/inner/vm_runner.rs
e2e-tests-rust/src/contracts/mod.rs

* Transactions to addresses that are not assigned to contracts produce warnings
* Eth calls to addresses that are not assigned to contracts produce warnings 
* Better diagnostics
```
cast send 0x1111111111111111111111111111111111111111 "transfer(address,uint256)" 0x70997970C51812dc3A010C7d01b50e0d17dc79C8 5000 --private-key 0xac0974bec39a17e36ba4a6b4d238ff944bacb478cbed5efcae784d7bf4f2ff80  --rpc-url http://localhost:8011 --chain 260
```
Response: 
```
Warning: Transaction 0xaca6…f4ec was sent to address 0x1111…1111, which is not associated with any contract.
```
```
cast call 0x1111111111111111111111111111111111111111 "method(address,uint256)(uint256)" "0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266" 1 --rpc-url http://localhost:8011
```
Response:
```
Warning: Read only call to address …
```

feat: warn of transactions to non-assigned addresses

---

Cargo.lock
Cargo.toml
SUPPORTED_APIS.md
crates/api_server/src/error.rs
crates/api_server/src/impls/zks.rs
crates/zksync_error/src/error/definitions.rs
e2e-tests-rust/Cargo.lock
e2e-tests-rust/Cargo.toml

Upgrades zksync-era version
We should use latest stable zksync-era for the next release

chore: upgrade zksync-era to v27.2.0

---

README.md
crates/cli/src/cli.rs
crates/cli/src/main.rs
crates/config/src/config.rs
crates/core/src/deps/mod.rs
crates/core/src/deps/system_contracts.rs
crates/core/src/node/in_memory.rs
crates/core/src/node/inner/fork_storage.rs
crates/core/src/node/inner/in_memory_inner.rs
crates/core/src/node/inner/mod.rs
crates/core/src/node/inner/vm_runner.rs
crates/core/src/system_contracts.rs

* Adds `--system-contracts-path` as a cli option, can only be used when system contract options are set to local
* Adds SystemContractsBuilder 
* Allows for custom path to be specified for system contract usage
* Currently only way was to set env var of ZKSYNC_HOME which also depends on the path being `./contracts/system-contracts`) whereas now devs (protocol team) can simply specify the era-contracts repo.
```bash
./target/release/anvil-zksync --dev-system-contracts local --system-contracts-path ./system-contracts --protocol-version 28
```
Once merged / released, can specify in action as such:
```bash
- name: Use anvil-zksync for testing
uses: …
```

feat: add cli option for local system contracts usage

---

.github/workflows/release.yml

To fix issues with wrong tags for pre-release generation when the pre-release was pointing to latest `main` instead of the commit that triggered the workflow.

ci: use proper target commit for manual pre-releases

---

Cargo.lock

* bumps dep version
* cargo-deny complains

fix: crossbeam-channel dep from rust advisory

---

crates/core/src/node/error.rs
crates/core/src/node/in_memory.rs
crates/core/src/node/inner/vm_runner.rs
crates/traces/src/lib.rs
crates/traces/src/writer.rs
crates/types/src/traces.rs

* Cherry picks commits [fd9fec0](https://github.com/matter-labs/anvil-zksync/pull/645/commits/fd9fec0ebba72073a21dee8d34cba17f543193ee), and [aa7f1aa](https://github.com/matter-labs/anvil-zksync/pull/645/commits/aa7f1aaec31b6aec0eb0b82e1d6c64bbb567206c) 
* Updates `convert_call_to_call_trace` to determine the execution result based on individual call
* Adds condition check earlier for constructing call trace so its not done when verbosity levels are unused
* cherry picked commits Closes #662 
* Closes #641 
Running:
```
./target/release/anvil-zksync -vvv replay_tx --fork-url sepolia-testnet 0x4fb92f25e8a5653aeae89e55e0c5311c2639a1733fec7aa0726b12fc2cc64224
```
The 3 displayed `Revert: Error function_selector` is equal to the number of revert reasons for the raw call trace in the correct …

fix: fix revert messages being appended to every call

---

crates/cli/src/cli.rs

fix: sophon testnet url typo

---

.github/workflows/bump-homebrew-formula.yml
Formula/anvil-zksync.rb

This is WIP until `bump-homebrew-formula.yaml` is complete as we need to bump the sha hash for each versioned release. 
* Adds homebrew formula for improved installation
* Adds GH workflow for bumping version and sha hash upon versioned releases
* Folks that want to use anvil-zksync but not foundry-zksync, for folks that want to install anvil-zksync not have their foundry installation overridden
* Make it easier to install 
* Script needs to reflect latest versioned release available
**Example usage:**
```bash
brew tap matter-labs/anvil-zksync
brew install anvil-zksync
brew update
brew upgrade anvil-zksync
```

feat: add homebrew formula for improved installation

---

Cargo.lock
Cargo.toml
crates/core/build.rs
crates/zksync_error/resources/error-model-dump.json

* updated zksync-error version
* updated zksync-error interface in `build.rs`
* Now zksync-error implements a link remapping that allows substituting `anvil.json` hosted on Github with its local modified copy. 
Intended as transparent.

feat: update zksync-error version to support overrides

---

crates/core/src/deps/mod.rs
crates/core/src/node/inner/fork_storage.rs

Closes #676 
Looks like an ancient bug, surprised we only caught it just now
Zero values in local storage are treated as missing values when sometimes they are legitimate zeroes

fix: respect zero value in local storage

---

.github/workflows/build-push-docker.yml
.github/workflows/e2e-docker.yml

Older v0.16.x buildx action is using outdated github service for caching.

fix: update docker buildx for proper containers caching

---

e2e-tests-rust/tests/evm.rs
e2e-tests-rust/tests/l1.rs

* Bumps timeout from 10 secs to 60s
* CI for e2e-rust-tests regularly fail due to L1 tests so bump timeout accordingly 

fix: address timeout issue in CI

---

crates/api_server/src/impls/eth.rs
crates/core/src/node/eth.rs
crates/core/src/node/in_memory.rs
crates/core/src/node/mod.rs
crates/core/src/node/state_override.rs
e2e-tests/test/eth-apis.test.ts

Adds support for overrides in `eth_call` using the logic from core.
Cherry-picked from https://github.com/matter-labs/anvil-zksync/pull/697 with a test added.

feat: Support state overrides in eth_call

---

crates/core/src/node/inner/in_memory_inner.rs

Alternative to #709 
Matches core's behavior - nonce is set at the API level before being passed to estimation logic instead of mocking storage value which is error-prone.
Old approach lead to issues with EVM interpreter based deployments (among other corner cases)

fix: set call request's nonce during estimation

---

crates/core/src/node/inner/in_memory_inner.rs

Upper limit got lowered in #702 but we did not account for the potential pubdata cost. This PR fixes it
SSO deployment tests are hitting the upper bound and are failing on 0.6.2

fix: account for pubdata cost in estimation bounds

---

crates/traces/src/lib.rs
crates/types/src/traces.rs

Fixes #712 
This fix is pretty dirty but a proper one would have to be done on zksync-era side to stop it from stringifying errors pre-emptively.
Better DevX

fix: preserve human-readable revert message

---

crates/core/src/node/eth.rs

anvil-zksync equivalent of https://github.com/matter-labs/zksync-era/pull/3833
Matching core's behavior

fix: return deployment nonce for contracts in `eth_getTransactionCount`

---

crates/core/src/node/in_memory.rs

Increases `MAX_TX_SIZE` from `1_000_000` to `1_200_000`
Needed to support certain blob unit tests in era-contracts, now that max number of blobs is 9.

feat: increase max transaction size

---

crates/api_server/src/error.rs
crates/core/src/formatter/errors/view.rs
crates/core/src/node/inner/in_memory_inner.rs
crates/zksync_error/resources/error-model-dump.json
crates/zksync_error/src/error/definitions.rs
e2e-tests-rust/src/ext.rs
e2e-tests-rust/src/test_contracts/mod.rs
e2e-tests-rust/tests/revert.rs
etc/errors/anvil.json

*  The revert reasons are communicated in `data` field of the JSON RPC error object
* Reported in https://github.com/zkSync-Community-Hub/zksync-developers/discussions/1042 
* This is used by [hardhat-chai-matchers](https://github.com/NomicFoundation/hardhat/blob/main/packages/hardhat-chai-matchers/src/internal/reverted/utils.ts#L63)
Tests failing in https://github.com/safe-global/safe-smart-account caught the breaking change.
Bug: 
After this fix:

fix: revert reasons not communicated to hardhat

---

.github/workflows/release.yml

* use nightly for binary build
* zksyncos uses it

fix: remove stable usage for binary build due to zksyncos

---

.github/workflows/build-stable.yaml
Cargo.toml
crates/api_server/Cargo.toml
crates/api_server/src/impls/anvil_zks.rs
crates/cli/Cargo.toml
crates/core/Cargo.toml
crates/core/src/lib.rs
crates/core/src/node/debug.rs
crates/core/src/node/eth.rs
crates/core/src/node/keys.rs
crates/core/src/node/mod.rs
crates/core/src/node/zksync_os/mock/mod.rs
crates/core/src/node/zksync_os/mod.rs
crates/core/src/node/zksync_os/real/helpers.rs
crates/core/src/node/zksync_os/real/mod.rs
crates/l1_sidecar/Cargo.toml

Puts zksync os behind a feature, but makes it enabled by default.
This is needed to keep foundry-zksync on stable, as it doesn't care about zksync os.
Also adds a CI check to make sure we don't loose ability to build code on stable.

feat: feature gate zksync os

---

docs/book/src/SUMMARY.md
docs/book/src/guides/l1_l2_testing.md

* Adds guide for showcasing L1-L2 communication for local testing
* Guides educate folks on usage
```
npm run test
> test
> hardhat test --network anvilZKsync
Cross-chain vault unlock (ethers + hardhat only)
✔ should deploy AccessKey on L1, Vault on L2, then unlock (12727ms)
1 passing (13s)
```

feat: adds l1-l2 testing guide to mdbook

---

.github/workflows/docs.yaml

* Restore zksync-error crate formatting changes during docs deployment
* Currently breaks the deploy docs ci flow

fix: workaround to fix deploy docs ci issue

---

Cargo.lock
e2e-tests-rust/tests/l1.rs

* Bumps tracing-subscriber dep to latest 
* Bumps sleep timeout for auto execute e2e test
* Cargo deny flagged version as a concern
* Ubuntu was consistently failing due to not enough sleep time between test runs

fix: adjust timeout for autoexecute
